// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: OmniFlix/streampay/v1/params.proto

package types

import (
	cosmossdk_io_math "cosmossdk.io/math"
	fmt "fmt"
	_ "github.com/cosmos/cosmos-sdk/types"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type Params struct {
	StreamPaymentFeePercentage cosmossdk_io_math.LegacyDec `protobuf:"bytes,1,opt,name=stream_payment_fee_percentage,json=streamPaymentFeePercentage,proto3,customtype=cosmossdk.io/math.LegacyDec" json:"stream_payment_fee_percentage" yaml:"stream_payment_fee_percentage"`
}

func (m *Params) Reset()         { *m = Params{} }
func (m *Params) String() string { return proto.CompactTextString(m) }
func (*Params) ProtoMessage()    {}
func (*Params) Descriptor() ([]byte, []int) {
	return fileDescriptor_f8d8e5be08a0a998, []int{0}
}
func (m *Params) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Params) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Params.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Params) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Params.Merge(m, src)
}
func (m *Params) XXX_Size() int {
	return m.Size()
}
func (m *Params) XXX_DiscardUnknown() {
	xxx_messageInfo_Params.DiscardUnknown(m)
}

var xxx_messageInfo_Params proto.InternalMessageInfo

func init() {
	proto.RegisterType((*Params)(nil), "OmniFlix.streampay.v1.Params")
}

func init() {
	proto.RegisterFile("OmniFlix/streampay/v1/params.proto", fileDescriptor_f8d8e5be08a0a998)
}

var fileDescriptor_f8d8e5be08a0a998 = []byte{
	// 270 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x90, 0xb1, 0x4a, 0xf4, 0x40,
	0x14, 0x46, 0x33, 0xcd, 0xc2, 0x9f, 0x72, 0xf9, 0x05, 0x89, 0x38, 0x91, 0x60, 0x61, 0x35, 0x43,
	0xb0, 0xb3, 0x5c, 0x64, 0x1b, 0x15, 0x83, 0xa5, 0x4d, 0xb8, 0x19, 0xaf, 0xd9, 0xe0, 0x4e, 0x66,
	0xc8, 0x8c, 0xc1, 0x79, 0x09, 0xb1, 0xf5, 0x8d, 0x52, 0x6e, 0x29, 0x16, 0x41, 0x93, 0x37, 0xf0,
	0x09, 0xc4, 0x0c, 0x2e, 0x16, 0x62, 0xf7, 0xc1, 0x39, 0x1c, 0xb8, 0x37, 0x4c, 0x2e, 0x65, 0x5d,
	0x2d, 0xd7, 0xd5, 0x03, 0x37, 0xb6, 0x41, 0x90, 0x1a, 0x1c, 0x6f, 0x53, 0xae, 0xa1, 0x01, 0x69,
	0x98, 0x6e, 0x94, 0x55, 0xf3, 0x9d, 0x6f, 0x87, 0x6d, 0x1d, 0xd6, 0xa6, 0xd1, 0xff, 0x52, 0x95,
	0x6a, 0x32, 0xf8, 0xd7, 0xf2, 0x72, 0x44, 0x85, 0x32, 0x52, 0x19, 0x5e, 0x80, 0x41, 0xde, 0xa6,
	0x05, 0x5a, 0x48, 0xb9, 0x50, 0x55, 0xed, 0x79, 0xf2, 0x4c, 0xc2, 0x59, 0x36, 0xd5, 0xe7, 0x8f,
	0x24, 0xdc, 0xf7, 0xc5, 0x5c, 0x83, 0x93, 0x58, 0xdb, 0xfc, 0x16, 0x31, 0xd7, 0xd8, 0x08, 0xac,
	0x2d, 0x94, 0xb8, 0x4b, 0x0e, 0xc8, 0xd1, 0xbf, 0xc5, 0x59, 0xd7, 0xc7, 0xc1, 0x6b, 0x1f, 0xef,
	0xf9, 0xb4, 0xb9, 0xb9, 0x63, 0x95, 0xe2, 0x12, 0xec, 0x8a, 0x9d, 0x63, 0x09, 0xc2, 0x9d, 0xa2,
	0xf8, 0xe8, 0xe3, 0x43, 0x07, 0x72, 0x7d, 0x92, 0xfc, 0x59, 0x4c, 0xae, 0x22, 0xcf, 0x33, 0x8f,
	0x97, 0x88, 0xd9, 0x16, 0x2e, 0x2e, 0xba, 0x77, 0x1a, 0x74, 0x03, 0x25, 0x9b, 0x81, 0x92, 0xb7,
	0x81, 0x92, 0xa7, 0x91, 0x06, 0x9b, 0x91, 0x06, 0x2f, 0x23, 0x0d, 0xae, 0x79, 0x59, 0xd9, 0xd5,
	0x7d, 0xc1, 0x84, 0x92, 0xfc, 0x97, 0xaf, 0xfd, 0xdc, 0xd6, 0x69, 0x34, 0xc5, 0x6c, 0xba, 0xf8,
	0xf8, 0x33, 0x00, 0x00, 0xff, 0xff, 0xb6, 0x9b, 0x0c, 0xf9, 0x64, 0x01, 0x00, 0x00,
}

func (m *Params) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Params) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Params) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size := m.StreamPaymentFeePercentage.Size()
		i -= size
		if _, err := m.StreamPaymentFeePercentage.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintParams(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func encodeVarintParams(dAtA []byte, offset int, v uint64) int {
	offset -= sovParams(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *Params) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.StreamPaymentFeePercentage.Size()
	n += 1 + l + sovParams(uint64(l))
	return n
}

func sovParams(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozParams(x uint64) (n int) {
	return sovParams(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *Params) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowParams
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Params: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Params: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field StreamPaymentFeePercentage", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.StreamPaymentFeePercentage.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipParams(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthParams
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipParams(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowParams
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowParams
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowParams
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthParams
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupParams
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthParams
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthParams        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowParams          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupParams = fmt.Errorf("proto: unexpected end of group")
)
