// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: streampay/v1/streampay.proto

package types

import (
	fmt "fmt"
	types "github.com/cosmos/cosmos-sdk/types"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	github_com_gogo_protobuf_types "github.com/gogo/protobuf/types"
	_ "google.golang.org/protobuf/types/known/timestamppb"
	io "io"
	math "math"
	math_bits "math/bits"
	time "time"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf
var _ = time.Kitchen

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type StreamType int32

const (
	TypeDelayed    StreamType = 0
	TypeContinuous StreamType = 1
	TypePeriodic   StreamType = 2
)

var StreamType_name = map[int32]string{
	0: "STREAM_PAYMENT_TYPE_DELAYED",
	1: "STREAM_PAYMENT_TYPE_CONTINUOUS",
	2: "STREAM_PAYMENT_TYPE_PERIODIC",
}

var StreamType_value = map[string]int32{
	"STREAM_PAYMENT_TYPE_DELAYED":    0,
	"STREAM_PAYMENT_TYPE_CONTINUOUS": 1,
	"STREAM_PAYMENT_TYPE_PERIODIC":   2,
}

func (x StreamType) String() string {
	return proto.EnumName(StreamType_name, int32(x))
}

func (StreamType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_3c74fe2874a05ff4, []int{0}
}

type StreamStatus int32

const (
	StatusActive    StreamStatus = 0
	StatusCompleted StreamStatus = 1
	StatusCancelled StreamStatus = 2
)

var StreamStatus_name = map[int32]string{
	0: "STREAM_PAYMENT_STATUS_ACTIVE",
	1: "STREAM_PAYMENT_STATUS_COMPLETED",
	2: "STREAM_PAYMENT_STATUS_CANCELLED",
}

var StreamStatus_value = map[string]int32{
	"STREAM_PAYMENT_STATUS_ACTIVE":    0,
	"STREAM_PAYMENT_STATUS_COMPLETED": 1,
	"STREAM_PAYMENT_STATUS_CANCELLED": 2,
}

func (x StreamStatus) String() string {
	return proto.EnumName(StreamStatus_name, int32(x))
}

func (StreamStatus) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_3c74fe2874a05ff4, []int{1}
}

type StreamPayment struct {
	Id             string       `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Sender         string       `protobuf:"bytes,2,opt,name=sender,proto3" json:"sender,omitempty"`
	Recipient      string       `protobuf:"bytes,3,opt,name=recipient,proto3" json:"recipient,omitempty"`
	TotalAmount    types.Coin   `protobuf:"bytes,4,opt,name=total_amount,json=totalAmount,proto3,castrepeated=github.com/cosmos/cosmos-sdk/types.Coin" json:"total_amount" yaml:"total_amount"`
	StreamType     StreamType   `protobuf:"varint,5,opt,name=stream_type,json=streamType,proto3,enum=OmniFlix.streampay.v1.StreamType" json:"stream_type,omitempty" yaml:"stream_type"`
	Periods        []*Period    `protobuf:"bytes,6,rep,name=periods,proto3" json:"periods,omitempty"`
	Cancellable    bool         `protobuf:"varint,7,opt,name=cancellable,proto3" json:"cancellable,omitempty"`
	StartTime      time.Time    `protobuf:"bytes,8,opt,name=start_time,json=startTime,proto3,stdtime" json:"start_time" yaml:"start_time"`
	EndTime        time.Time    `protobuf:"bytes,9,opt,name=end_time,json=endTime,proto3,stdtime" json:"end_time" yaml:"end_time"`
	StreamedAmount types.Coin   `protobuf:"bytes,10,opt,name=streamed_amount,json=streamedAmount,proto3,castrepeated=github.com/cosmos/cosmos-sdk/types.Coin" json:"streamed_amount" yaml:"streamed_amount"`
	ClaimedAmount  types.Coin   `protobuf:"bytes,11,opt,name=claimed_amount,json=claimedAmount,proto3,castrepeated=github.com/cosmos/cosmos-sdk/types.Coin" json:"claimed_amount" yaml:"claimed_amount"`
	LastClaimedAt  time.Time    `protobuf:"bytes,12,opt,name=last_claimed_at,json=lastClaimedAt,proto3,stdtime" json:"last_claimed_at" yaml:"last_claimed_at"`
	Status         StreamStatus `protobuf:"varint,13,opt,name=status,proto3,enum=OmniFlix.streampay.v1.StreamStatus" json:"status,omitempty"`
}

func (m *StreamPayment) Reset()         { *m = StreamPayment{} }
func (m *StreamPayment) String() string { return proto.CompactTextString(m) }
func (*StreamPayment) ProtoMessage()    {}
func (*StreamPayment) Descriptor() ([]byte, []int) {
	return fileDescriptor_3c74fe2874a05ff4, []int{0}
}
func (m *StreamPayment) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *StreamPayment) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_StreamPayment.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *StreamPayment) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StreamPayment.Merge(m, src)
}
func (m *StreamPayment) XXX_Size() int {
	return m.Size()
}
func (m *StreamPayment) XXX_DiscardUnknown() {
	xxx_messageInfo_StreamPayment.DiscardUnknown(m)
}

var xxx_messageInfo_StreamPayment proto.InternalMessageInfo

func (m *StreamPayment) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *StreamPayment) GetSender() string {
	if m != nil {
		return m.Sender
	}
	return ""
}

func (m *StreamPayment) GetRecipient() string {
	if m != nil {
		return m.Recipient
	}
	return ""
}

func (m *StreamPayment) GetTotalAmount() types.Coin {
	if m != nil {
		return m.TotalAmount
	}
	return types.Coin{}
}

func (m *StreamPayment) GetStreamType() StreamType {
	if m != nil {
		return m.StreamType
	}
	return TypeDelayed
}

func (m *StreamPayment) GetPeriods() []*Period {
	if m != nil {
		return m.Periods
	}
	return nil
}

func (m *StreamPayment) GetCancellable() bool {
	if m != nil {
		return m.Cancellable
	}
	return false
}

func (m *StreamPayment) GetStartTime() time.Time {
	if m != nil {
		return m.StartTime
	}
	return time.Time{}
}

func (m *StreamPayment) GetEndTime() time.Time {
	if m != nil {
		return m.EndTime
	}
	return time.Time{}
}

func (m *StreamPayment) GetStreamedAmount() types.Coin {
	if m != nil {
		return m.StreamedAmount
	}
	return types.Coin{}
}

func (m *StreamPayment) GetClaimedAmount() types.Coin {
	if m != nil {
		return m.ClaimedAmount
	}
	return types.Coin{}
}

func (m *StreamPayment) GetLastClaimedAt() time.Time {
	if m != nil {
		return m.LastClaimedAt
	}
	return time.Time{}
}

func (m *StreamPayment) GetStatus() StreamStatus {
	if m != nil {
		return m.Status
	}
	return StatusActive
}

type Period struct {
	Amount   int64 `protobuf:"varint,1,opt,name=amount,proto3" json:"amount,omitempty" yaml:"amount"`
	Duration int64 `protobuf:"varint,2,opt,name=duration,proto3" json:"duration,omitempty" yaml:"duration"`
}

func (m *Period) Reset()         { *m = Period{} }
func (m *Period) String() string { return proto.CompactTextString(m) }
func (*Period) ProtoMessage()    {}
func (*Period) Descriptor() ([]byte, []int) {
	return fileDescriptor_3c74fe2874a05ff4, []int{1}
}
func (m *Period) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Period) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Period.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Period) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Period.Merge(m, src)
}
func (m *Period) XXX_Size() int {
	return m.Size()
}
func (m *Period) XXX_DiscardUnknown() {
	xxx_messageInfo_Period.DiscardUnknown(m)
}

var xxx_messageInfo_Period proto.InternalMessageInfo

func (m *Period) GetAmount() int64 {
	if m != nil {
		return m.Amount
	}
	return 0
}

func (m *Period) GetDuration() int64 {
	if m != nil {
		return m.Duration
	}
	return 0
}

func init() {
	proto.RegisterEnum("OmniFlix.streampay.v1.StreamType", StreamType_name, StreamType_value)
	proto.RegisterEnum("OmniFlix.streampay.v1.StreamStatus", StreamStatus_name, StreamStatus_value)
	proto.RegisterType((*StreamPayment)(nil), "OmniFlix.streampay.v1.StreamPayment")
	proto.RegisterType((*Period)(nil), "OmniFlix.streampay.v1.Period")
}

func init() { proto.RegisterFile("streampay/v1/streampay.proto", fileDescriptor_3c74fe2874a05ff4) }

var fileDescriptor_3c74fe2874a05ff4 = []byte{
	// 855 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x95, 0x4f, 0x6f, 0xe3, 0x44,
	0x18, 0xc6, 0x33, 0x69, 0x49, 0xd3, 0x49, 0xf3, 0x67, 0xa7, 0x6c, 0x65, 0xb2, 0x5d, 0xdb, 0x84,
	0x03, 0x61, 0x25, 0x6c, 0x5a, 0x24, 0x84, 0x40, 0x1c, 0x12, 0xc7, 0x2b, 0x22, 0xb5, 0x4d, 0xe4,
	0xb8, 0x88, 0xee, 0x25, 0x9a, 0xd8, 0xb3, 0xc1, 0xc2, 0xf6, 0x44, 0xf1, 0xa4, 0x22, 0x77, 0x0e,
	0x10, 0x09, 0x69, 0xbf, 0x40, 0x4f, 0xdc, 0x38, 0xf1, 0x01, 0xf8, 0x00, 0x3d, 0xee, 0x91, 0x53,
	0x16, 0xb5, 0xdf, 0xa0, 0x9f, 0x00, 0x79, 0xc6, 0x4e, 0x5c, 0x14, 0xb6, 0xda, 0x53, 0x67, 0xde,
	0x79, 0x7f, 0x8f, 0xdf, 0x79, 0xde, 0xb7, 0x13, 0x78, 0x18, 0xb1, 0x29, 0xc1, 0xc1, 0x04, 0xcf,
	0xf5, 0xcb, 0x23, 0x7d, 0xb5, 0xd1, 0x26, 0x53, 0xca, 0x28, 0x7a, 0xdc, 0x0b, 0x42, 0xef, 0xb9,
	0xef, 0xfd, 0xa4, 0xad, 0x4f, 0x2e, 0x8f, 0xea, 0xb2, 0x43, 0xa3, 0x80, 0x46, 0xfa, 0x08, 0x47,
	0x44, 0xbf, 0x3c, 0x1a, 0x11, 0x86, 0x8f, 0x74, 0x87, 0x7a, 0xa1, 0xc0, 0xea, 0xef, 0x8f, 0xe9,
	0x98, 0xf2, 0xa5, 0x1e, 0xaf, 0x92, 0xa8, 0x32, 0xa6, 0x74, 0xec, 0x13, 0x9d, 0xef, 0x46, 0xb3,
	0x97, 0x3a, 0xf3, 0x02, 0x12, 0x31, 0x1c, 0x4c, 0x44, 0x42, 0xe3, 0xd7, 0x22, 0x2c, 0x0f, 0xf8,
	0x77, 0xfa, 0x78, 0x1e, 0x90, 0x90, 0xa1, 0x0a, 0xcc, 0x7b, 0xae, 0x04, 0x54, 0xd0, 0xdc, 0xb5,
	0xf2, 0x9e, 0x8b, 0x0e, 0x60, 0x21, 0x22, 0xa1, 0x4b, 0xa6, 0x52, 0x9e, 0xc7, 0x92, 0x1d, 0x3a,
	0x84, 0xbb, 0x53, 0xe2, 0x78, 0x13, 0x8f, 0x84, 0x4c, 0xda, 0xe2, 0x47, 0xeb, 0x00, 0xfa, 0x19,
	0xc0, 0x3d, 0x46, 0x19, 0xf6, 0x87, 0x38, 0xa0, 0xb3, 0x90, 0x49, 0xdb, 0x2a, 0x68, 0x96, 0x8e,
	0x3f, 0xd0, 0xc4, 0x35, 0xb4, 0xf8, 0x1a, 0x5a, 0x72, 0x0d, 0xcd, 0xa0, 0x5e, 0xd8, 0x7e, 0x7e,
	0xbd, 0x54, 0x72, 0x77, 0x4b, 0x65, 0x7f, 0x8e, 0x03, 0xff, 0xab, 0x46, 0x16, 0x6e, 0xfc, 0xf1,
	0x46, 0xf9, 0x78, 0xec, 0xb1, 0x1f, 0x66, 0x23, 0xcd, 0xa1, 0x81, 0x9e, 0x58, 0x21, 0xfe, 0x7c,
	0x1a, 0xb9, 0x3f, 0xea, 0x6c, 0x3e, 0x21, 0x11, 0xd7, 0xb1, 0x4a, 0x9c, 0x6c, 0x71, 0x10, 0xbd,
	0x80, 0x25, 0xe1, 0xe2, 0x30, 0xce, 0x90, 0xde, 0x53, 0x41, 0xb3, 0x72, 0xfc, 0xa1, 0xb6, 0xd1,
	0x62, 0x4d, 0xf8, 0x60, 0xcf, 0x27, 0xa4, 0x7d, 0x70, 0xb7, 0x54, 0x90, 0x28, 0x24, 0xc3, 0x37,
	0x2c, 0x18, 0xad, 0x72, 0xd0, 0x37, 0x70, 0x67, 0x42, 0xa6, 0x1e, 0x75, 0x23, 0xa9, 0xa0, 0x6e,
	0x35, 0x4b, 0xc7, 0x4f, 0xff, 0x47, 0xb7, 0xcf, 0xb3, 0xda, 0xdb, 0xd7, 0x4b, 0x05, 0x58, 0x29,
	0x83, 0x54, 0x58, 0x72, 0x70, 0xe8, 0x10, 0xdf, 0xc7, 0x23, 0x9f, 0x48, 0x3b, 0x2a, 0x68, 0x16,
	0xad, 0x6c, 0x08, 0x7d, 0x0f, 0x61, 0xc4, 0xf0, 0x94, 0x0d, 0xe3, 0xa6, 0x49, 0x45, 0x6e, 0x60,
	0x5d, 0x13, 0x1d, 0xd5, 0xd2, 0x8e, 0x6a, 0x76, 0xda, 0xd1, 0xf6, 0xd3, 0xc4, 0xc1, 0x47, 0x69,
	0xe1, 0x29, 0xdb, 0x78, 0xf5, 0x46, 0x01, 0xd6, 0x2e, 0x0f, 0xc4, 0xe9, 0xc8, 0x82, 0x45, 0x12,
	0xba, 0x42, 0x77, 0xf7, 0x41, 0xdd, 0x27, 0x89, 0x6e, 0x55, 0xe8, 0xa6, 0xa4, 0x50, 0xdd, 0x21,
	0xa1, 0xcb, 0x35, 0x7f, 0x03, 0xb0, 0x2a, 0xae, 0x4d, 0xdc, 0xb4, 0xe9, 0xf0, 0xa1, 0xa6, 0x77,
	0x13, 0xe9, 0x83, 0xac, 0xd7, 0x2b, 0xfe, 0x9d, 0xfa, 0x5e, 0x49, 0xe1, 0xa4, 0xf5, 0x0b, 0x00,
	0x2b, 0x8e, 0x8f, 0xbd, 0x4c, 0x39, 0xa5, 0x87, 0xca, 0xf9, 0x36, 0x29, 0xe7, 0xb1, 0x28, 0xe7,
	0x3e, 0xfe, 0x4e, 0xd5, 0x94, 0x13, 0x36, 0x29, 0xe6, 0x25, 0xac, 0xfa, 0x38, 0x62, 0xc3, 0x95,
	0x22, 0x93, 0xf6, 0x1e, 0xf4, 0xbd, 0x71, 0xdf, 0x9c, 0xff, 0x08, 0x08, 0xfb, 0xcb, 0x71, 0xd4,
	0x48, 0xbe, 0xc5, 0xd0, 0xd7, 0xb0, 0x10, 0x31, 0xcc, 0x66, 0x91, 0x54, 0xe6, 0xa3, 0xfe, 0xd1,
	0x5b, 0x47, 0x7d, 0xc0, 0x53, 0xad, 0x04, 0x69, 0xb8, 0xb0, 0x20, 0x46, 0x15, 0x7d, 0x02, 0x0b,
	0x89, 0x65, 0xf1, 0x3b, 0xb0, 0xd5, 0x7e, 0x74, 0xb7, 0x54, 0xca, 0xa2, 0x8a, 0xc4, 0x0b, 0x2b,
	0x49, 0x40, 0x3a, 0x2c, 0xba, 0xb3, 0x29, 0x66, 0x1e, 0x0d, 0xf9, 0x03, 0xb1, 0xd5, 0xde, 0x5f,
	0x8f, 0x4a, 0x7a, 0xd2, 0xb0, 0x56, 0x49, 0xcf, 0xfe, 0x04, 0x10, 0xae, 0xff, 0xd3, 0xd0, 0x67,
	0xf0, 0xc9, 0xc0, 0xb6, 0xcc, 0xd6, 0xe9, 0xb0, 0xdf, 0xba, 0x38, 0x35, 0xcf, 0xec, 0xa1, 0x7d,
	0xd1, 0x37, 0x87, 0x1d, 0xf3, 0xa4, 0x75, 0x61, 0x76, 0x6a, 0xb9, 0x7a, 0x75, 0x71, 0xa5, 0x96,
	0xe2, 0xd4, 0x0e, 0xf1, 0xf1, 0x9c, 0xb8, 0xe8, 0x0b, 0x28, 0x6f, 0x22, 0x8c, 0xde, 0x99, 0xdd,
	0x3d, 0x3b, 0xef, 0x9d, 0x0f, 0x6a, 0xa0, 0x8e, 0x16, 0x57, 0x6a, 0x25, 0x86, 0x0c, 0x1a, 0x32,
	0x2f, 0x9c, 0xd1, 0x59, 0x84, 0x8e, 0xe1, 0xe1, 0x26, 0xae, 0x6f, 0x5a, 0xdd, 0x5e, 0xa7, 0x6b,
	0xd4, 0xf2, 0xf5, 0xda, 0xe2, 0x4a, 0xdd, 0x8b, 0x29, 0x61, 0x83, 0xe7, 0xd4, 0xb7, 0x7f, 0xf9,
	0x5d, 0xce, 0x3d, 0xfb, 0x0b, 0xc0, 0xbd, 0xac, 0x63, 0x1b, 0xa4, 0x06, 0x76, 0xcb, 0x3e, 0x1f,
	0x0c, 0x5b, 0x86, 0xdd, 0xfd, 0xce, 0xac, 0xe5, 0x84, 0x94, 0xc8, 0x6e, 0x39, 0xcc, 0xbb, 0x24,
	0xe8, 0x4b, 0xa8, 0x6c, 0x66, 0x8c, 0xde, 0x69, 0xff, 0xc4, 0xb4, 0xcd, 0x4e, 0x0d, 0xd4, 0xf7,
	0x17, 0x57, 0x6a, 0x55, 0x60, 0x06, 0x0d, 0x26, 0x3e, 0x61, 0xc4, 0x7d, 0x0b, 0xd9, 0x3a, 0x33,
	0xcc, 0x93, 0x13, 0xb3, 0x53, 0xcb, 0xdf, 0x23, 0xc5, 0x1b, 0x42, 0x5c, 0x51, 0x7e, 0xbb, 0x7b,
	0x7d, 0x23, 0x83, 0xd7, 0x37, 0x32, 0xf8, 0xe7, 0x46, 0x06, 0xaf, 0x6e, 0xe5, 0xdc, 0xeb, 0x5b,
	0x39, 0xf7, 0xf7, 0xad, 0x9c, 0x7b, 0xa1, 0x67, 0xc6, 0x39, 0x1d, 0x94, 0xf5, 0x0f, 0x92, 0x9e,
	0x5d, 0xf3, 0xd9, 0x1e, 0x15, 0xf8, 0x98, 0x7e, 0xfe, 0x6f, 0x00, 0x00, 0x00, 0xff, 0xff, 0xda,
	0xbc, 0x28, 0xc7, 0xc3, 0x06, 0x00, 0x00,
}

func (m *StreamPayment) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *StreamPayment) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *StreamPayment) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Status != 0 {
		i = encodeVarintStreampay(dAtA, i, uint64(m.Status))
		i--
		dAtA[i] = 0x68
	}
	n1, err1 := github_com_gogo_protobuf_types.StdTimeMarshalTo(m.LastClaimedAt, dAtA[i-github_com_gogo_protobuf_types.SizeOfStdTime(m.LastClaimedAt):])
	if err1 != nil {
		return 0, err1
	}
	i -= n1
	i = encodeVarintStreampay(dAtA, i, uint64(n1))
	i--
	dAtA[i] = 0x62
	{
		size, err := m.ClaimedAmount.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintStreampay(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x5a
	{
		size, err := m.StreamedAmount.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintStreampay(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x52
	n4, err4 := github_com_gogo_protobuf_types.StdTimeMarshalTo(m.EndTime, dAtA[i-github_com_gogo_protobuf_types.SizeOfStdTime(m.EndTime):])
	if err4 != nil {
		return 0, err4
	}
	i -= n4
	i = encodeVarintStreampay(dAtA, i, uint64(n4))
	i--
	dAtA[i] = 0x4a
	n5, err5 := github_com_gogo_protobuf_types.StdTimeMarshalTo(m.StartTime, dAtA[i-github_com_gogo_protobuf_types.SizeOfStdTime(m.StartTime):])
	if err5 != nil {
		return 0, err5
	}
	i -= n5
	i = encodeVarintStreampay(dAtA, i, uint64(n5))
	i--
	dAtA[i] = 0x42
	if m.Cancellable {
		i--
		if m.Cancellable {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x38
	}
	if len(m.Periods) > 0 {
		for iNdEx := len(m.Periods) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Periods[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintStreampay(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x32
		}
	}
	if m.StreamType != 0 {
		i = encodeVarintStreampay(dAtA, i, uint64(m.StreamType))
		i--
		dAtA[i] = 0x28
	}
	{
		size, err := m.TotalAmount.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintStreampay(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x22
	if len(m.Recipient) > 0 {
		i -= len(m.Recipient)
		copy(dAtA[i:], m.Recipient)
		i = encodeVarintStreampay(dAtA, i, uint64(len(m.Recipient)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.Sender) > 0 {
		i -= len(m.Sender)
		copy(dAtA[i:], m.Sender)
		i = encodeVarintStreampay(dAtA, i, uint64(len(m.Sender)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Id) > 0 {
		i -= len(m.Id)
		copy(dAtA[i:], m.Id)
		i = encodeVarintStreampay(dAtA, i, uint64(len(m.Id)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *Period) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Period) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Period) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Duration != 0 {
		i = encodeVarintStreampay(dAtA, i, uint64(m.Duration))
		i--
		dAtA[i] = 0x10
	}
	if m.Amount != 0 {
		i = encodeVarintStreampay(dAtA, i, uint64(m.Amount))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func encodeVarintStreampay(dAtA []byte, offset int, v uint64) int {
	offset -= sovStreampay(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *StreamPayment) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Id)
	if l > 0 {
		n += 1 + l + sovStreampay(uint64(l))
	}
	l = len(m.Sender)
	if l > 0 {
		n += 1 + l + sovStreampay(uint64(l))
	}
	l = len(m.Recipient)
	if l > 0 {
		n += 1 + l + sovStreampay(uint64(l))
	}
	l = m.TotalAmount.Size()
	n += 1 + l + sovStreampay(uint64(l))
	if m.StreamType != 0 {
		n += 1 + sovStreampay(uint64(m.StreamType))
	}
	if len(m.Periods) > 0 {
		for _, e := range m.Periods {
			l = e.Size()
			n += 1 + l + sovStreampay(uint64(l))
		}
	}
	if m.Cancellable {
		n += 2
	}
	l = github_com_gogo_protobuf_types.SizeOfStdTime(m.StartTime)
	n += 1 + l + sovStreampay(uint64(l))
	l = github_com_gogo_protobuf_types.SizeOfStdTime(m.EndTime)
	n += 1 + l + sovStreampay(uint64(l))
	l = m.StreamedAmount.Size()
	n += 1 + l + sovStreampay(uint64(l))
	l = m.ClaimedAmount.Size()
	n += 1 + l + sovStreampay(uint64(l))
	l = github_com_gogo_protobuf_types.SizeOfStdTime(m.LastClaimedAt)
	n += 1 + l + sovStreampay(uint64(l))
	if m.Status != 0 {
		n += 1 + sovStreampay(uint64(m.Status))
	}
	return n
}

func (m *Period) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Amount != 0 {
		n += 1 + sovStreampay(uint64(m.Amount))
	}
	if m.Duration != 0 {
		n += 1 + sovStreampay(uint64(m.Duration))
	}
	return n
}

func sovStreampay(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozStreampay(x uint64) (n int) {
	return sovStreampay(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *StreamPayment) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowStreampay
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: StreamPayment: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: StreamPayment: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowStreampay
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthStreampay
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthStreampay
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Id = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Sender", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowStreampay
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthStreampay
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthStreampay
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Sender = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Recipient", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowStreampay
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthStreampay
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthStreampay
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Recipient = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TotalAmount", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowStreampay
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthStreampay
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthStreampay
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.TotalAmount.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field StreamType", wireType)
			}
			m.StreamType = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowStreampay
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.StreamType |= StreamType(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Periods", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowStreampay
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthStreampay
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthStreampay
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Periods = append(m.Periods, &Period{})
			if err := m.Periods[len(m.Periods)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 7:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Cancellable", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowStreampay
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.Cancellable = bool(v != 0)
		case 8:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field StartTime", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowStreampay
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthStreampay
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthStreampay
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := github_com_gogo_protobuf_types.StdTimeUnmarshal(&m.StartTime, dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 9:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field EndTime", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowStreampay
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthStreampay
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthStreampay
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := github_com_gogo_protobuf_types.StdTimeUnmarshal(&m.EndTime, dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 10:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field StreamedAmount", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowStreampay
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthStreampay
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthStreampay
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.StreamedAmount.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 11:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ClaimedAmount", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowStreampay
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthStreampay
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthStreampay
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.ClaimedAmount.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 12:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field LastClaimedAt", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowStreampay
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthStreampay
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthStreampay
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := github_com_gogo_protobuf_types.StdTimeUnmarshal(&m.LastClaimedAt, dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 13:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Status", wireType)
			}
			m.Status = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowStreampay
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Status |= StreamStatus(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipStreampay(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthStreampay
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *Period) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowStreampay
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Period: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Period: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Amount", wireType)
			}
			m.Amount = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowStreampay
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Amount |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Duration", wireType)
			}
			m.Duration = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowStreampay
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Duration |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipStreampay(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthStreampay
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipStreampay(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowStreampay
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowStreampay
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowStreampay
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthStreampay
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupStreampay
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthStreampay
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthStreampay        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowStreampay          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupStreampay = fmt.Errorf("proto: unexpected end of group")
)
