// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: streampay/streampay.proto

package types

import (
	fmt "fmt"
	types "github.com/cosmos/cosmos-sdk/types"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	github_com_gogo_protobuf_types "github.com/gogo/protobuf/types"
	_ "google.golang.org/protobuf/types/known/timestamppb"
	io "io"
	math "math"
	math_bits "math/bits"
	time "time"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf
var _ = time.Kitchen

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type PaymentType int32

const (
	TypeDelayed    PaymentType = 0
	TypeContinuous PaymentType = 1
	TypePeriodic   PaymentType = 2
)

var PaymentType_name = map[int32]string{
	0: "PAYMENT_TYPE_DELAYED",
	1: "PAYMENT_TYPE_CONTINUOUS",
	2: "PAYMENT_TYPE_PERIODIC",
}

var PaymentType_value = map[string]int32{
	"PAYMENT_TYPE_DELAYED":    0,
	"PAYMENT_TYPE_CONTINUOUS": 1,
	"PAYMENT_TYPE_PERIODIC":   2,
}

func (x PaymentType) String() string {
	return proto.EnumName(PaymentType_name, int32(x))
}

func (PaymentType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_9fc790406387aa73, []int{0}
}

type PaymentStatus int32

const (
	StatusActive    PaymentStatus = 0
	StatusCompleted PaymentStatus = 1
	StatusCancelled PaymentStatus = 2
)

var PaymentStatus_name = map[int32]string{
	0: "PAYMENT_STATUS_ACTIVE",
	1: "PAYMENT_STATUS_COMPLETED",
	2: "PAYMENT_STATUS_CANCELLED",
}

var PaymentStatus_value = map[string]int32{
	"PAYMENT_STATUS_ACTIVE":    0,
	"PAYMENT_STATUS_COMPLETED": 1,
	"PAYMENT_STATUS_CANCELLED": 2,
}

func (x PaymentStatus) String() string {
	return proto.EnumName(PaymentStatus_name, int32(x))
}

func (PaymentStatus) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_9fc790406387aa73, []int{1}
}

type StreamPayment struct {
	Id             string        `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Sender         string        `protobuf:"bytes,2,opt,name=sender,proto3" json:"sender,omitempty"`
	Recipient      string        `protobuf:"bytes,3,opt,name=recipient,proto3" json:"recipient,omitempty"`
	TotalAmount    types.Coin    `protobuf:"bytes,4,opt,name=total_amount,json=totalAmount,proto3,castrepeated=github.com/cosmos/cosmos-sdk/types.Coin" json:"total_amount" yaml:"total_amount"`
	StreamType     PaymentType   `protobuf:"varint,5,opt,name=stream_type,json=streamType,proto3,enum=OmniFlix.streampay.v1.PaymentType" json:"stream_type,omitempty" yaml:"stream_type"`
	StartTime      time.Time     `protobuf:"bytes,6,opt,name=start_time,json=startTime,proto3,stdtime" json:"start_time" yaml:"start_time"`
	EndTime        time.Time     `protobuf:"bytes,7,opt,name=end_time,json=endTime,proto3,stdtime" json:"end_time" yaml:"end_time"`
	StreamedAmount types.Coin    `protobuf:"bytes,8,opt,name=streamed_amount,json=streamedAmount,proto3,castrepeated=github.com/cosmos/cosmos-sdk/types.Coin" json:"streamed_amount" yaml:"streamed_amount"`
	ClaimedAmount  types.Coin    `protobuf:"bytes,9,opt,name=claimed_amount,json=claimedAmount,proto3,castrepeated=github.com/cosmos/cosmos-sdk/types.Coin" json:"claimed_amount" yaml:"claimed_amount"`
	LastClaimedAt  time.Time     `protobuf:"bytes,10,opt,name=last_claimed_at,json=lastClaimedAt,proto3,stdtime" json:"last_claimed_at" yaml:"last_claimed_at"`
	Status         PaymentStatus `protobuf:"varint,11,opt,name=status,proto3,enum=OmniFlix.streampay.v1.PaymentStatus" json:"status,omitempty" yaml:"status"`
}

func (m *StreamPayment) Reset()         { *m = StreamPayment{} }
func (m *StreamPayment) String() string { return proto.CompactTextString(m) }
func (*StreamPayment) ProtoMessage()    {}
func (*StreamPayment) Descriptor() ([]byte, []int) {
	return fileDescriptor_9fc790406387aa73, []int{0}
}
func (m *StreamPayment) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *StreamPayment) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_StreamPayment.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *StreamPayment) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StreamPayment.Merge(m, src)
}
func (m *StreamPayment) XXX_Size() int {
	return m.Size()
}
func (m *StreamPayment) XXX_DiscardUnknown() {
	xxx_messageInfo_StreamPayment.DiscardUnknown(m)
}

var xxx_messageInfo_StreamPayment proto.InternalMessageInfo

func (m *StreamPayment) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *StreamPayment) GetSender() string {
	if m != nil {
		return m.Sender
	}
	return ""
}

func (m *StreamPayment) GetRecipient() string {
	if m != nil {
		return m.Recipient
	}
	return ""
}

func (m *StreamPayment) GetTotalAmount() types.Coin {
	if m != nil {
		return m.TotalAmount
	}
	return types.Coin{}
}

func (m *StreamPayment) GetStreamType() PaymentType {
	if m != nil {
		return m.StreamType
	}
	return TypeDelayed
}

func (m *StreamPayment) GetStartTime() time.Time {
	if m != nil {
		return m.StartTime
	}
	return time.Time{}
}

func (m *StreamPayment) GetEndTime() time.Time {
	if m != nil {
		return m.EndTime
	}
	return time.Time{}
}

func (m *StreamPayment) GetStreamedAmount() types.Coin {
	if m != nil {
		return m.StreamedAmount
	}
	return types.Coin{}
}

func (m *StreamPayment) GetClaimedAmount() types.Coin {
	if m != nil {
		return m.ClaimedAmount
	}
	return types.Coin{}
}

func (m *StreamPayment) GetLastClaimedAt() time.Time {
	if m != nil {
		return m.LastClaimedAt
	}
	return time.Time{}
}

func (m *StreamPayment) GetStatus() PaymentStatus {
	if m != nil {
		return m.Status
	}
	return StatusActive
}

func init() {
	proto.RegisterEnum("OmniFlix.streampay.v1.PaymentType", PaymentType_name, PaymentType_value)
	proto.RegisterEnum("OmniFlix.streampay.v1.PaymentStatus", PaymentStatus_name, PaymentStatus_value)
	proto.RegisterType((*StreamPayment)(nil), "OmniFlix.streampay.v1.StreamPayment")
}

func init() { proto.RegisterFile("streampay/streampay.proto", fileDescriptor_9fc790406387aa73) }

var fileDescriptor_9fc790406387aa73 = []byte{
	// 757 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x54, 0xcd, 0x6e, 0xda, 0x4c,
	0x14, 0xc5, 0x7c, 0xf9, 0x48, 0x18, 0xc2, 0x4f, 0x9c, 0x9f, 0x3a, 0x6e, 0x6b, 0x90, 0x55, 0xa9,
	0x69, 0xaa, 0xda, 0x22, 0xdd, 0x75, 0x07, 0xc6, 0x51, 0x91, 0x08, 0x20, 0x70, 0xaa, 0xa6, 0x5d,
	0x20, 0x63, 0x4f, 0xa8, 0x55, 0xdb, 0x83, 0xf0, 0x10, 0x95, 0x7d, 0x17, 0x15, 0x52, 0xa5, 0x3c,
	0x40, 0x59, 0x75, 0x53, 0xf5, 0x1d, 0xba, 0xcf, 0x32, 0xcb, 0xae, 0x48, 0x95, 0xbc, 0x41, 0x9e,
	0xa0, 0xf2, 0x8c, 0x4d, 0x4c, 0x14, 0x15, 0x65, 0xc5, 0xcc, 0xf5, 0x39, 0x67, 0xce, 0x3d, 0xf7,
	0x0a, 0xb0, 0xed, 0xe1, 0x01, 0xd4, 0x9d, 0xbe, 0x3e, 0x92, 0x67, 0x27, 0xa9, 0x3f, 0x40, 0x18,
	0xb1, 0x9b, 0x0d, 0xc7, 0xb5, 0xf6, 0x6d, 0xeb, 0x93, 0x74, 0xf3, 0xe5, 0xa4, 0xc8, 0x0b, 0x06,
	0xf2, 0x1c, 0xe4, 0xc9, 0x5d, 0xdd, 0x83, 0xf2, 0x49, 0xb1, 0x0b, 0xb1, 0x5e, 0x94, 0x0d, 0x64,
	0xb9, 0x94, 0xc6, 0x6f, 0xf4, 0x50, 0x0f, 0x91, 0xa3, 0xec, 0x9f, 0x82, 0x6a, 0xbe, 0x87, 0x50,
	0xcf, 0x86, 0x32, 0xb9, 0x75, 0x87, 0xc7, 0x32, 0xb6, 0x1c, 0xe8, 0x61, 0xdd, 0xe9, 0x53, 0x80,
	0xf8, 0x6b, 0x19, 0xa4, 0xdb, 0xe4, 0x9d, 0xa6, 0x3e, 0x72, 0xa0, 0x8b, 0xd9, 0x0c, 0x88, 0x5b,
	0x26, 0xc7, 0x14, 0x98, 0x9d, 0x64, 0x2b, 0x6e, 0x99, 0xec, 0x16, 0x48, 0x78, 0xd0, 0x35, 0xe1,
	0x80, 0x8b, 0x93, 0x5a, 0x70, 0x63, 0x1f, 0x81, 0xe4, 0x00, 0x1a, 0x56, 0xdf, 0x82, 0x2e, 0xe6,
	0xfe, 0x23, 0x9f, 0x6e, 0x0a, 0xec, 0x67, 0x06, 0xac, 0x62, 0x84, 0x75, 0xbb, 0xa3, 0x3b, 0x68,
	0xe8, 0x62, 0x6e, 0xa9, 0xc0, 0xec, 0xa4, 0xf6, 0xb6, 0x25, 0xda, 0x86, 0xe4, 0xb7, 0x21, 0x05,
	0x6d, 0x48, 0x0a, 0xb2, 0xdc, 0xf2, 0xfe, 0xd9, 0x34, 0x1f, 0xbb, 0x9e, 0xe6, 0xd7, 0x47, 0xba,
	0x63, 0xbf, 0x12, 0xa3, 0x64, 0xf1, 0xe7, 0x45, 0xfe, 0x69, 0xcf, 0xc2, 0x1f, 0x86, 0x5d, 0xc9,
	0x40, 0x8e, 0x1c, 0x44, 0x41, 0x7f, 0x5e, 0x78, 0xe6, 0x47, 0x19, 0x8f, 0xfa, 0xd0, 0x23, 0x3a,
	0xad, 0x14, 0x61, 0x96, 0x08, 0x91, 0x7d, 0x0f, 0x52, 0x34, 0xc5, 0x8e, 0x8f, 0xe0, 0xfe, 0x2f,
	0x30, 0x3b, 0x99, 0x3d, 0x51, 0xba, 0x33, 0x62, 0x29, 0x48, 0x40, 0x1b, 0xf5, 0x61, 0x79, 0xeb,
	0x7a, 0x9a, 0x67, 0xa9, 0x93, 0x88, 0x80, 0xd8, 0x02, 0xf4, 0xe6, 0x63, 0xd8, 0xb7, 0x00, 0x78,
	0x58, 0x1f, 0xe0, 0x8e, 0x1f, 0x2a, 0x97, 0x20, 0x0d, 0xf2, 0x12, 0x4d, 0x5c, 0x0a, 0x13, 0x97,
	0xb4, 0x30, 0xf1, 0xf2, 0xe3, 0xa0, 0xc3, 0xb5, 0x50, 0x37, 0xe4, 0x8a, 0xa7, 0x17, 0x79, 0xa6,
	0x95, 0x24, 0x05, 0x1f, 0xce, 0xb6, 0xc0, 0x0a, 0x74, 0x4d, 0xaa, 0xbb, 0xbc, 0x50, 0xf7, 0x61,
	0xa0, 0x9b, 0xa5, 0xba, 0x21, 0x93, 0xaa, 0x2e, 0x43, 0xd7, 0x24, 0x9a, 0x5f, 0x19, 0x90, 0xa5,
	0xe6, 0xa1, 0x19, 0x0e, 0x65, 0x65, 0xd1, 0x50, 0xaa, 0x81, 0xf4, 0x56, 0x34, 0x8a, 0x19, 0xff,
	0x5e, 0x73, 0xc9, 0x84, 0xe4, 0x60, 0x34, 0x63, 0x06, 0x64, 0x0c, 0x5b, 0xb7, 0x22, 0x76, 0x92,
	0x8b, 0xec, 0xbc, 0x0e, 0xec, 0x6c, 0x52, 0x3b, 0xf3, 0xf4, 0x7b, 0xb9, 0x49, 0x07, 0xdc, 0xc0,
	0xcc, 0x31, 0xc8, 0xda, 0xba, 0x87, 0x3b, 0x33, 0x45, 0xcc, 0x81, 0x85, 0xb9, 0x8b, 0xf3, 0xe1,
	0xdc, 0x12, 0xa0, 0xf1, 0xa7, 0xfd, 0xaa, 0x12, 0xbc, 0x85, 0xd9, 0x06, 0x48, 0x78, 0x58, 0xc7,
	0x43, 0x8f, 0x4b, 0x91, 0x55, 0x7c, 0xf2, 0xef, 0x55, 0x6c, 0x13, 0x6c, 0x79, 0xed, 0x7a, 0x9a,
	0x4f, 0xcf, 0x96, 0x06, 0x0f, 0x3d, 0xb1, 0x15, 0xc8, 0xec, 0x7e, 0x63, 0x40, 0x2a, 0xb2, 0xb7,
	0xec, 0x33, 0xb0, 0xd1, 0x2c, 0x1d, 0x1d, 0xa8, 0x75, 0xad, 0xa3, 0x1d, 0x35, 0xd5, 0x4e, 0x45,
	0xad, 0x95, 0x8e, 0xd4, 0x4a, 0x2e, 0xc6, 0x67, 0xc7, 0x93, 0x42, 0xca, 0xc7, 0x54, 0xa0, 0xad,
	0x8f, 0xa0, 0xc9, 0xca, 0xe0, 0xc1, 0x1c, 0x54, 0x69, 0xd4, 0xb5, 0x6a, 0xfd, 0xb0, 0x71, 0xd8,
	0xce, 0x31, 0x3c, 0x3b, 0x9e, 0x14, 0x32, 0x3e, 0x5a, 0x41, 0x2e, 0xb6, 0xdc, 0x21, 0x1a, 0x7a,
	0xec, 0x73, 0xb0, 0x39, 0x47, 0x68, 0xaa, 0xad, 0x6a, 0xa3, 0x52, 0x55, 0x72, 0x71, 0x3e, 0x37,
	0x9e, 0x14, 0x56, 0x7d, 0x78, 0x13, 0x0e, 0x2c, 0x64, 0x5a, 0x06, 0xbf, 0xf4, 0xe5, 0xbb, 0x10,
	0xdb, 0xfd, 0xc1, 0x80, 0xf4, 0x5c, 0x2f, 0x51, 0x91, 0xb6, 0x56, 0xd2, 0x0e, 0xdb, 0x9d, 0x92,
	0xa2, 0x55, 0xdf, 0xa8, 0xb9, 0x18, 0x15, 0xa1, 0xb0, 0x92, 0x81, 0xad, 0x13, 0xc8, 0x16, 0x01,
	0x77, 0x0b, 0xac, 0x34, 0x0e, 0x9a, 0x35, 0x55, 0x53, 0x2b, 0x39, 0x86, 0x5f, 0x1f, 0x4f, 0x0a,
	0x59, 0x8a, 0x57, 0x90, 0xd3, 0xb7, 0x21, 0x86, 0xe6, 0x5d, 0x94, 0x52, 0x5d, 0x51, 0x6b, 0x35,
	0xb5, 0x92, 0x8b, 0xcf, 0x51, 0x74, 0xd7, 0x80, 0xb6, 0x0d, 0x4d, 0x6a, 0xb5, 0x5c, 0x3d, 0xbb,
	0x14, 0x98, 0xf3, 0x4b, 0x81, 0xf9, 0x73, 0x29, 0x30, 0xa7, 0x57, 0x42, 0xec, 0xfc, 0x4a, 0x88,
	0xfd, 0xbe, 0x12, 0x62, 0xef, 0xe4, 0xc8, 0x52, 0x85, 0xe3, 0xba, 0xf9, 0xdb, 0x96, 0xa3, 0x67,
	0xb2, 0x61, 0xdd, 0x04, 0x59, 0x96, 0x97, 0x7f, 0x03, 0x00, 0x00, 0xff, 0xff, 0xa1, 0x9e, 0x9c,
	0xfa, 0xe6, 0x05, 0x00, 0x00,
}

func (m *StreamPayment) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *StreamPayment) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *StreamPayment) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Status != 0 {
		i = encodeVarintStreampay(dAtA, i, uint64(m.Status))
		i--
		dAtA[i] = 0x58
	}
	n1, err1 := github_com_gogo_protobuf_types.StdTimeMarshalTo(m.LastClaimedAt, dAtA[i-github_com_gogo_protobuf_types.SizeOfStdTime(m.LastClaimedAt):])
	if err1 != nil {
		return 0, err1
	}
	i -= n1
	i = encodeVarintStreampay(dAtA, i, uint64(n1))
	i--
	dAtA[i] = 0x52
	{
		size, err := m.ClaimedAmount.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintStreampay(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x4a
	{
		size, err := m.StreamedAmount.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintStreampay(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x42
	n4, err4 := github_com_gogo_protobuf_types.StdTimeMarshalTo(m.EndTime, dAtA[i-github_com_gogo_protobuf_types.SizeOfStdTime(m.EndTime):])
	if err4 != nil {
		return 0, err4
	}
	i -= n4
	i = encodeVarintStreampay(dAtA, i, uint64(n4))
	i--
	dAtA[i] = 0x3a
	n5, err5 := github_com_gogo_protobuf_types.StdTimeMarshalTo(m.StartTime, dAtA[i-github_com_gogo_protobuf_types.SizeOfStdTime(m.StartTime):])
	if err5 != nil {
		return 0, err5
	}
	i -= n5
	i = encodeVarintStreampay(dAtA, i, uint64(n5))
	i--
	dAtA[i] = 0x32
	if m.StreamType != 0 {
		i = encodeVarintStreampay(dAtA, i, uint64(m.StreamType))
		i--
		dAtA[i] = 0x28
	}
	{
		size, err := m.TotalAmount.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintStreampay(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x22
	if len(m.Recipient) > 0 {
		i -= len(m.Recipient)
		copy(dAtA[i:], m.Recipient)
		i = encodeVarintStreampay(dAtA, i, uint64(len(m.Recipient)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.Sender) > 0 {
		i -= len(m.Sender)
		copy(dAtA[i:], m.Sender)
		i = encodeVarintStreampay(dAtA, i, uint64(len(m.Sender)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Id) > 0 {
		i -= len(m.Id)
		copy(dAtA[i:], m.Id)
		i = encodeVarintStreampay(dAtA, i, uint64(len(m.Id)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintStreampay(dAtA []byte, offset int, v uint64) int {
	offset -= sovStreampay(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *StreamPayment) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Id)
	if l > 0 {
		n += 1 + l + sovStreampay(uint64(l))
	}
	l = len(m.Sender)
	if l > 0 {
		n += 1 + l + sovStreampay(uint64(l))
	}
	l = len(m.Recipient)
	if l > 0 {
		n += 1 + l + sovStreampay(uint64(l))
	}
	l = m.TotalAmount.Size()
	n += 1 + l + sovStreampay(uint64(l))
	if m.StreamType != 0 {
		n += 1 + sovStreampay(uint64(m.StreamType))
	}
	l = github_com_gogo_protobuf_types.SizeOfStdTime(m.StartTime)
	n += 1 + l + sovStreampay(uint64(l))
	l = github_com_gogo_protobuf_types.SizeOfStdTime(m.EndTime)
	n += 1 + l + sovStreampay(uint64(l))
	l = m.StreamedAmount.Size()
	n += 1 + l + sovStreampay(uint64(l))
	l = m.ClaimedAmount.Size()
	n += 1 + l + sovStreampay(uint64(l))
	l = github_com_gogo_protobuf_types.SizeOfStdTime(m.LastClaimedAt)
	n += 1 + l + sovStreampay(uint64(l))
	if m.Status != 0 {
		n += 1 + sovStreampay(uint64(m.Status))
	}
	return n
}

func sovStreampay(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozStreampay(x uint64) (n int) {
	return sovStreampay(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *StreamPayment) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowStreampay
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: StreamPayment: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: StreamPayment: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowStreampay
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthStreampay
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthStreampay
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Id = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Sender", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowStreampay
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthStreampay
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthStreampay
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Sender = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Recipient", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowStreampay
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthStreampay
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthStreampay
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Recipient = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TotalAmount", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowStreampay
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthStreampay
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthStreampay
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.TotalAmount.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field StreamType", wireType)
			}
			m.StreamType = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowStreampay
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.StreamType |= PaymentType(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field StartTime", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowStreampay
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthStreampay
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthStreampay
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := github_com_gogo_protobuf_types.StdTimeUnmarshal(&m.StartTime, dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field EndTime", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowStreampay
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthStreampay
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthStreampay
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := github_com_gogo_protobuf_types.StdTimeUnmarshal(&m.EndTime, dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 8:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field StreamedAmount", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowStreampay
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthStreampay
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthStreampay
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.StreamedAmount.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 9:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ClaimedAmount", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowStreampay
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthStreampay
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthStreampay
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.ClaimedAmount.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 10:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field LastClaimedAt", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowStreampay
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthStreampay
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthStreampay
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := github_com_gogo_protobuf_types.StdTimeUnmarshal(&m.LastClaimedAt, dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 11:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Status", wireType)
			}
			m.Status = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowStreampay
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Status |= PaymentStatus(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipStreampay(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthStreampay
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipStreampay(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowStreampay
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowStreampay
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowStreampay
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthStreampay
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupStreampay
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthStreampay
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthStreampay        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowStreampay          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupStreampay = fmt.Errorf("proto: unexpected end of group")
)
