// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: streampay/v1/tx.proto

package types

import (
	context "context"
	fmt "fmt"
	types "github.com/cosmos/cosmos-sdk/types"
	_ "github.com/gogo/protobuf/gogoproto"
	grpc1 "github.com/gogo/protobuf/grpc"
	proto "github.com/gogo/protobuf/proto"
	github_com_gogo_protobuf_types "github.com/gogo/protobuf/types"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	_ "google.golang.org/protobuf/types/known/durationpb"
	io "io"
	math "math"
	math_bits "math/bits"
	time "time"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf
var _ = time.Kitchen

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type MsgStreamSend struct {
	Sender      string        `protobuf:"bytes,1,opt,name=sender,proto3" json:"sender,omitempty"`
	Recipient   string        `protobuf:"bytes,2,opt,name=recipient,proto3" json:"recipient,omitempty"`
	Amount      types.Coin    `protobuf:"bytes,3,opt,name=amount,proto3,castrepeated=github.com/cosmos/cosmos-sdk/types.Coin" json:"amount"`
	Duration    time.Duration `protobuf:"bytes,4,opt,name=duration,proto3,stdduration" json:"duration"`
	StreamType  StreamType    `protobuf:"varint,5,opt,name=stream_type,json=streamType,proto3,enum=OmniFlix.streampay.v1.StreamType" json:"stream_type,omitempty" yaml:"stream_type"`
	Periods     []*Period     `protobuf:"bytes,6,rep,name=periods,proto3" json:"periods,omitempty"`
	Cancellable bool          `protobuf:"varint,7,opt,name=cancellable,proto3" json:"cancellable,omitempty"`
	Fee         types.Coin    `protobuf:"bytes,8,opt,name=fee,proto3,castrepeated=github.com/cosmos/cosmos-sdk/types.Coin" json:"fee"`
}

func (m *MsgStreamSend) Reset()         { *m = MsgStreamSend{} }
func (m *MsgStreamSend) String() string { return proto.CompactTextString(m) }
func (*MsgStreamSend) ProtoMessage()    {}
func (*MsgStreamSend) Descriptor() ([]byte, []int) {
	return fileDescriptor_40773333fbee058d, []int{0}
}
func (m *MsgStreamSend) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgStreamSend) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgStreamSend.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgStreamSend) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgStreamSend.Merge(m, src)
}
func (m *MsgStreamSend) XXX_Size() int {
	return m.Size()
}
func (m *MsgStreamSend) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgStreamSend.DiscardUnknown(m)
}

var xxx_messageInfo_MsgStreamSend proto.InternalMessageInfo

func (m *MsgStreamSend) GetSender() string {
	if m != nil {
		return m.Sender
	}
	return ""
}

func (m *MsgStreamSend) GetRecipient() string {
	if m != nil {
		return m.Recipient
	}
	return ""
}

func (m *MsgStreamSend) GetAmount() types.Coin {
	if m != nil {
		return m.Amount
	}
	return types.Coin{}
}

func (m *MsgStreamSend) GetDuration() time.Duration {
	if m != nil {
		return m.Duration
	}
	return 0
}

func (m *MsgStreamSend) GetStreamType() StreamType {
	if m != nil {
		return m.StreamType
	}
	return TypeDelayed
}

func (m *MsgStreamSend) GetPeriods() []*Period {
	if m != nil {
		return m.Periods
	}
	return nil
}

func (m *MsgStreamSend) GetCancellable() bool {
	if m != nil {
		return m.Cancellable
	}
	return false
}

func (m *MsgStreamSend) GetFee() types.Coin {
	if m != nil {
		return m.Fee
	}
	return types.Coin{}
}

type MsgStreamSendResponse struct {
}

func (m *MsgStreamSendResponse) Reset()         { *m = MsgStreamSendResponse{} }
func (m *MsgStreamSendResponse) String() string { return proto.CompactTextString(m) }
func (*MsgStreamSendResponse) ProtoMessage()    {}
func (*MsgStreamSendResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_40773333fbee058d, []int{1}
}
func (m *MsgStreamSendResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgStreamSendResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgStreamSendResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgStreamSendResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgStreamSendResponse.Merge(m, src)
}
func (m *MsgStreamSendResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgStreamSendResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgStreamSendResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgStreamSendResponse proto.InternalMessageInfo

type MsgStopStream struct {
	StreamId string `protobuf:"bytes,1,opt,name=stream_id,json=streamId,proto3" json:"stream_id,omitempty" yaml:"stream_id"`
	Sender   string `protobuf:"bytes,2,opt,name=sender,proto3" json:"sender,omitempty"`
}

func (m *MsgStopStream) Reset()         { *m = MsgStopStream{} }
func (m *MsgStopStream) String() string { return proto.CompactTextString(m) }
func (*MsgStopStream) ProtoMessage()    {}
func (*MsgStopStream) Descriptor() ([]byte, []int) {
	return fileDescriptor_40773333fbee058d, []int{2}
}
func (m *MsgStopStream) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgStopStream) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgStopStream.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgStopStream) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgStopStream.Merge(m, src)
}
func (m *MsgStopStream) XXX_Size() int {
	return m.Size()
}
func (m *MsgStopStream) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgStopStream.DiscardUnknown(m)
}

var xxx_messageInfo_MsgStopStream proto.InternalMessageInfo

func (m *MsgStopStream) GetStreamId() string {
	if m != nil {
		return m.StreamId
	}
	return ""
}

func (m *MsgStopStream) GetSender() string {
	if m != nil {
		return m.Sender
	}
	return ""
}

type MsgStopStreamResponse struct {
}

func (m *MsgStopStreamResponse) Reset()         { *m = MsgStopStreamResponse{} }
func (m *MsgStopStreamResponse) String() string { return proto.CompactTextString(m) }
func (*MsgStopStreamResponse) ProtoMessage()    {}
func (*MsgStopStreamResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_40773333fbee058d, []int{3}
}
func (m *MsgStopStreamResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgStopStreamResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgStopStreamResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgStopStreamResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgStopStreamResponse.Merge(m, src)
}
func (m *MsgStopStreamResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgStopStreamResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgStopStreamResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgStopStreamResponse proto.InternalMessageInfo

type MsgClaimStreamedAmount struct {
	StreamId string `protobuf:"bytes,1,opt,name=stream_id,json=streamId,proto3" json:"stream_id,omitempty" yaml:"stream_id"`
	Claimer  string `protobuf:"bytes,2,opt,name=claimer,proto3" json:"claimer,omitempty"`
}

func (m *MsgClaimStreamedAmount) Reset()         { *m = MsgClaimStreamedAmount{} }
func (m *MsgClaimStreamedAmount) String() string { return proto.CompactTextString(m) }
func (*MsgClaimStreamedAmount) ProtoMessage()    {}
func (*MsgClaimStreamedAmount) Descriptor() ([]byte, []int) {
	return fileDescriptor_40773333fbee058d, []int{4}
}
func (m *MsgClaimStreamedAmount) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgClaimStreamedAmount) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgClaimStreamedAmount.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgClaimStreamedAmount) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgClaimStreamedAmount.Merge(m, src)
}
func (m *MsgClaimStreamedAmount) XXX_Size() int {
	return m.Size()
}
func (m *MsgClaimStreamedAmount) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgClaimStreamedAmount.DiscardUnknown(m)
}

var xxx_messageInfo_MsgClaimStreamedAmount proto.InternalMessageInfo

func (m *MsgClaimStreamedAmount) GetStreamId() string {
	if m != nil {
		return m.StreamId
	}
	return ""
}

func (m *MsgClaimStreamedAmount) GetClaimer() string {
	if m != nil {
		return m.Claimer
	}
	return ""
}

type MsgClaimStreamedAmountResponse struct {
}

func (m *MsgClaimStreamedAmountResponse) Reset()         { *m = MsgClaimStreamedAmountResponse{} }
func (m *MsgClaimStreamedAmountResponse) String() string { return proto.CompactTextString(m) }
func (*MsgClaimStreamedAmountResponse) ProtoMessage()    {}
func (*MsgClaimStreamedAmountResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_40773333fbee058d, []int{5}
}
func (m *MsgClaimStreamedAmountResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgClaimStreamedAmountResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgClaimStreamedAmountResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgClaimStreamedAmountResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgClaimStreamedAmountResponse.Merge(m, src)
}
func (m *MsgClaimStreamedAmountResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgClaimStreamedAmountResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgClaimStreamedAmountResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgClaimStreamedAmountResponse proto.InternalMessageInfo

func init() {
	proto.RegisterType((*MsgStreamSend)(nil), "OmniFlix.streampay.v1.MsgStreamSend")
	proto.RegisterType((*MsgStreamSendResponse)(nil), "OmniFlix.streampay.v1.MsgStreamSendResponse")
	proto.RegisterType((*MsgStopStream)(nil), "OmniFlix.streampay.v1.MsgStopStream")
	proto.RegisterType((*MsgStopStreamResponse)(nil), "OmniFlix.streampay.v1.MsgStopStreamResponse")
	proto.RegisterType((*MsgClaimStreamedAmount)(nil), "OmniFlix.streampay.v1.MsgClaimStreamedAmount")
	proto.RegisterType((*MsgClaimStreamedAmountResponse)(nil), "OmniFlix.streampay.v1.MsgClaimStreamedAmountResponse")
}

func init() { proto.RegisterFile("streampay/v1/tx.proto", fileDescriptor_40773333fbee058d) }

var fileDescriptor_40773333fbee058d = []byte{
	// 591 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x54, 0x4f, 0x8b, 0xd3, 0x40,
	0x1c, 0x6d, 0xb6, 0x6b, 0xb7, 0x3b, 0x45, 0x91, 0x71, 0xb7, 0xc6, 0xb2, 0x26, 0x31, 0x08, 0xf6,
	0xe0, 0xce, 0xd0, 0x8a, 0x17, 0x41, 0xc4, 0xac, 0x08, 0x7b, 0x28, 0x4a, 0xd6, 0x53, 0x11, 0x34,
	0x7f, 0x66, 0xe3, 0x60, 0x92, 0x09, 0x99, 0xb4, 0x6c, 0xf1, 0xec, 0xdd, 0xa3, 0x9f, 0xc1, 0x0f,
	0x22, 0x3d, 0xee, 0xd1, 0x53, 0x57, 0xda, 0x6f, 0xb0, 0x9f, 0x40, 0x92, 0x49, 0xd2, 0x54, 0xda,
	0x45, 0xc5, 0x53, 0x67, 0x7e, 0x7f, 0xde, 0xcb, 0x7b, 0x79, 0x29, 0xd8, 0xe7, 0x49, 0x4c, 0xac,
	0x20, 0xb2, 0x26, 0x78, 0xdc, 0xc3, 0xc9, 0x19, 0x8a, 0x62, 0x96, 0x30, 0xb8, 0xff, 0x2a, 0x08,
	0xe9, 0x4b, 0x9f, 0x9e, 0xa1, 0xb2, 0x8f, 0xc6, 0xbd, 0x8e, 0xe2, 0x30, 0x1e, 0x30, 0x8e, 0x6d,
	0x8b, 0x13, 0x3c, 0xee, 0xd9, 0x24, 0xb1, 0x7a, 0xd8, 0x61, 0x34, 0x14, 0x6b, 0x9d, 0x3d, 0x8f,
	0x79, 0x2c, 0x3b, 0xe2, 0xf4, 0x94, 0x57, 0x15, 0x8f, 0x31, 0xcf, 0x27, 0x38, 0xbb, 0xd9, 0xa3,
	0x53, 0xec, 0x8e, 0x62, 0x2b, 0xa1, 0xac, 0xd8, 0x3a, 0x58, 0x79, 0x86, 0x25, 0x61, 0xd6, 0xd5,
	0x3f, 0x6f, 0x83, 0xeb, 0x03, 0xee, 0x9d, 0x64, 0xe5, 0x13, 0x12, 0xba, 0xb0, 0x0d, 0x1a, 0x9c,
	0x84, 0x2e, 0x89, 0x65, 0x49, 0x93, 0xba, 0xbb, 0x66, 0x7e, 0x83, 0x07, 0x60, 0x37, 0x26, 0x0e,
	0x8d, 0x28, 0x09, 0x13, 0x79, 0x2b, 0x6b, 0x2d, 0x0b, 0xd0, 0x06, 0x0d, 0x2b, 0x60, 0xa3, 0x30,
	0x91, 0xeb, 0x9a, 0xd4, 0x6d, 0xf5, 0xef, 0x20, 0x21, 0x06, 0xa5, 0x62, 0x50, 0x2e, 0x06, 0x1d,
	0x31, 0x1a, 0x1a, 0x78, 0x3a, 0x53, 0x6b, 0xdf, 0x2e, 0xd4, 0x07, 0x1e, 0x4d, 0x3e, 0x8c, 0x6c,
	0xe4, 0xb0, 0x00, 0xe7, 0xca, 0xc5, 0xcf, 0x21, 0x77, 0x3f, 0xe2, 0x64, 0x12, 0x11, 0x9e, 0x2d,
	0x98, 0x39, 0x32, 0x7c, 0x06, 0x9a, 0x85, 0x36, 0x79, 0x3b, 0x67, 0x11, 0xe2, 0x51, 0x21, 0x1e,
	0xbd, 0xc8, 0x07, 0x8c, 0x66, 0xca, 0xf2, 0xf5, 0x42, 0x95, 0xcc, 0x72, 0x09, 0x0e, 0x41, 0x4b,
	0xe8, 0x7f, 0x97, 0xa2, 0xcb, 0xd7, 0x34, 0xa9, 0x7b, 0xa3, 0x7f, 0x0f, 0xad, 0x7d, 0x1b, 0x48,
	0x58, 0xf2, 0x66, 0x12, 0x11, 0xa3, 0x7d, 0x39, 0x53, 0xe1, 0xc4, 0x0a, 0xfc, 0x27, 0x7a, 0x65,
	0x5f, 0x37, 0x01, 0x2f, 0x67, 0xe0, 0x53, 0xb0, 0x13, 0x91, 0x98, 0x32, 0x97, 0xcb, 0x0d, 0xad,
	0xde, 0x6d, 0xf5, 0xef, 0x6e, 0xc0, 0x7d, 0x9d, 0x4d, 0x19, 0xdb, 0xd3, 0x99, 0x2a, 0x99, 0xc5,
	0x0e, 0xd4, 0x40, 0xcb, 0xb1, 0x42, 0x87, 0xf8, 0xbe, 0x65, 0xfb, 0x44, 0xde, 0xd1, 0xa4, 0x6e,
	0xd3, 0xac, 0x96, 0xe0, 0x5b, 0x50, 0x3f, 0x25, 0x44, 0x6e, 0xfe, 0x77, 0x7b, 0x53, 0x58, 0xfd,
	0x36, 0xd8, 0x5f, 0x89, 0x81, 0x49, 0x78, 0xc4, 0x42, 0x4e, 0xf4, 0x61, 0x9e, 0x0f, 0x16, 0x89,
	0x26, 0xec, 0x81, 0xdd, 0xdc, 0x04, 0xea, 0x8a, 0x88, 0x18, 0x7b, 0x97, 0x33, 0xf5, 0xe6, 0x8a,
	0x3f, 0xd4, 0xd5, 0xcd, 0xa6, 0x38, 0x1f, 0x57, 0x23, 0xb5, 0x55, 0x8d, 0x54, 0x49, 0x5a, 0x60,
	0x97, 0xa4, 0x04, 0xb4, 0x07, 0xdc, 0x3b, 0xf2, 0x2d, 0x1a, 0x88, 0x0e, 0x71, 0x9f, 0x8b, 0x0c,
	0xfc, 0x03, 0xbb, 0x0c, 0x76, 0x9c, 0x14, 0xa9, 0xa4, 0x2f, 0xae, 0xba, 0x06, 0x94, 0xf5, 0x34,
	0xc5, 0x83, 0xf4, 0xbf, 0x6f, 0x81, 0xfa, 0x80, 0x7b, 0xf0, 0x3d, 0x00, 0x95, 0x4f, 0xe4, 0xfe,
	0x86, 0x57, 0xbb, 0xe2, 0x60, 0xe7, 0xe1, 0x9f, 0x4c, 0x15, 0x4c, 0x82, 0xa1, 0x34, 0xf9, 0x4a,
	0x86, 0x62, 0xea, 0x6a, 0x86, 0xdf, 0x4d, 0x85, 0x9f, 0xc0, 0xad, 0x75, 0x8e, 0x1e, 0x6e, 0x06,
	0x59, 0x33, 0xde, 0x79, 0xfc, 0x57, 0xe3, 0x05, 0xb9, 0x71, 0x3c, 0x9d, 0x2b, 0xd2, 0xf9, 0x5c,
	0x91, 0x7e, 0xce, 0x15, 0xe9, 0xcb, 0x42, 0xa9, 0x9d, 0x2f, 0x94, 0xda, 0x8f, 0x85, 0x52, 0x1b,
	0xe2, 0x4a, 0x4e, 0x0b, 0xe8, 0xe5, 0xdf, 0x14, 0xae, 0x9e, 0xb3, 0xd0, 0xda, 0x8d, 0xec, 0x63,
	0x7f, 0xf4, 0x2b, 0x00, 0x00, 0xff, 0xff, 0x25, 0xbf, 0xdd, 0x05, 0x5d, 0x05, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// MsgClient is the client API for Msg service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MsgClient interface {
	StreamSend(ctx context.Context, in *MsgStreamSend, opts ...grpc.CallOption) (*MsgStreamSendResponse, error)
	StopStream(ctx context.Context, in *MsgStopStream, opts ...grpc.CallOption) (*MsgStopStreamResponse, error)
	ClaimStreamedAmount(ctx context.Context, in *MsgClaimStreamedAmount, opts ...grpc.CallOption) (*MsgClaimStreamedAmountResponse, error)
}

type msgClient struct {
	cc grpc1.ClientConn
}

func NewMsgClient(cc grpc1.ClientConn) MsgClient {
	return &msgClient{cc}
}

func (c *msgClient) StreamSend(ctx context.Context, in *MsgStreamSend, opts ...grpc.CallOption) (*MsgStreamSendResponse, error) {
	out := new(MsgStreamSendResponse)
	err := c.cc.Invoke(ctx, "/OmniFlix.streampay.v1.Msg/StreamSend", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) StopStream(ctx context.Context, in *MsgStopStream, opts ...grpc.CallOption) (*MsgStopStreamResponse, error) {
	out := new(MsgStopStreamResponse)
	err := c.cc.Invoke(ctx, "/OmniFlix.streampay.v1.Msg/StopStream", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) ClaimStreamedAmount(ctx context.Context, in *MsgClaimStreamedAmount, opts ...grpc.CallOption) (*MsgClaimStreamedAmountResponse, error) {
	out := new(MsgClaimStreamedAmountResponse)
	err := c.cc.Invoke(ctx, "/OmniFlix.streampay.v1.Msg/ClaimStreamedAmount", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MsgServer is the server API for Msg service.
type MsgServer interface {
	StreamSend(context.Context, *MsgStreamSend) (*MsgStreamSendResponse, error)
	StopStream(context.Context, *MsgStopStream) (*MsgStopStreamResponse, error)
	ClaimStreamedAmount(context.Context, *MsgClaimStreamedAmount) (*MsgClaimStreamedAmountResponse, error)
}

// UnimplementedMsgServer can be embedded to have forward compatible implementations.
type UnimplementedMsgServer struct {
}

func (*UnimplementedMsgServer) StreamSend(ctx context.Context, req *MsgStreamSend) (*MsgStreamSendResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StreamSend not implemented")
}
func (*UnimplementedMsgServer) StopStream(ctx context.Context, req *MsgStopStream) (*MsgStopStreamResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StopStream not implemented")
}
func (*UnimplementedMsgServer) ClaimStreamedAmount(ctx context.Context, req *MsgClaimStreamedAmount) (*MsgClaimStreamedAmountResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ClaimStreamedAmount not implemented")
}

func RegisterMsgServer(s grpc1.Server, srv MsgServer) {
	s.RegisterService(&_Msg_serviceDesc, srv)
}

func _Msg_StreamSend_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgStreamSend)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).StreamSend(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/OmniFlix.streampay.v1.Msg/StreamSend",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).StreamSend(ctx, req.(*MsgStreamSend))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_StopStream_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgStopStream)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).StopStream(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/OmniFlix.streampay.v1.Msg/StopStream",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).StopStream(ctx, req.(*MsgStopStream))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_ClaimStreamedAmount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgClaimStreamedAmount)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).ClaimStreamedAmount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/OmniFlix.streampay.v1.Msg/ClaimStreamedAmount",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).ClaimStreamedAmount(ctx, req.(*MsgClaimStreamedAmount))
	}
	return interceptor(ctx, in, info, handler)
}

var _Msg_serviceDesc = grpc.ServiceDesc{
	ServiceName: "OmniFlix.streampay.v1.Msg",
	HandlerType: (*MsgServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "StreamSend",
			Handler:    _Msg_StreamSend_Handler,
		},
		{
			MethodName: "StopStream",
			Handler:    _Msg_StopStream_Handler,
		},
		{
			MethodName: "ClaimStreamedAmount",
			Handler:    _Msg_ClaimStreamedAmount_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "streampay/v1/tx.proto",
}

func (m *MsgStreamSend) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgStreamSend) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgStreamSend) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.Fee.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintTx(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x42
	if m.Cancellable {
		i--
		if m.Cancellable {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x38
	}
	if len(m.Periods) > 0 {
		for iNdEx := len(m.Periods) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Periods[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintTx(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x32
		}
	}
	if m.StreamType != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.StreamType))
		i--
		dAtA[i] = 0x28
	}
	n2, err2 := github_com_gogo_protobuf_types.StdDurationMarshalTo(m.Duration, dAtA[i-github_com_gogo_protobuf_types.SizeOfStdDuration(m.Duration):])
	if err2 != nil {
		return 0, err2
	}
	i -= n2
	i = encodeVarintTx(dAtA, i, uint64(n2))
	i--
	dAtA[i] = 0x22
	{
		size, err := m.Amount.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintTx(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x1a
	if len(m.Recipient) > 0 {
		i -= len(m.Recipient)
		copy(dAtA[i:], m.Recipient)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Recipient)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Sender) > 0 {
		i -= len(m.Sender)
		copy(dAtA[i:], m.Sender)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Sender)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgStreamSendResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgStreamSendResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgStreamSendResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *MsgStopStream) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgStopStream) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgStopStream) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Sender) > 0 {
		i -= len(m.Sender)
		copy(dAtA[i:], m.Sender)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Sender)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.StreamId) > 0 {
		i -= len(m.StreamId)
		copy(dAtA[i:], m.StreamId)
		i = encodeVarintTx(dAtA, i, uint64(len(m.StreamId)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgStopStreamResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgStopStreamResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgStopStreamResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *MsgClaimStreamedAmount) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgClaimStreamedAmount) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgClaimStreamedAmount) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Claimer) > 0 {
		i -= len(m.Claimer)
		copy(dAtA[i:], m.Claimer)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Claimer)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.StreamId) > 0 {
		i -= len(m.StreamId)
		copy(dAtA[i:], m.StreamId)
		i = encodeVarintTx(dAtA, i, uint64(len(m.StreamId)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgClaimStreamedAmountResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgClaimStreamedAmountResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgClaimStreamedAmountResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func encodeVarintTx(dAtA []byte, offset int, v uint64) int {
	offset -= sovTx(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *MsgStreamSend) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Sender)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.Recipient)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = m.Amount.Size()
	n += 1 + l + sovTx(uint64(l))
	l = github_com_gogo_protobuf_types.SizeOfStdDuration(m.Duration)
	n += 1 + l + sovTx(uint64(l))
	if m.StreamType != 0 {
		n += 1 + sovTx(uint64(m.StreamType))
	}
	if len(m.Periods) > 0 {
		for _, e := range m.Periods {
			l = e.Size()
			n += 1 + l + sovTx(uint64(l))
		}
	}
	if m.Cancellable {
		n += 2
	}
	l = m.Fee.Size()
	n += 1 + l + sovTx(uint64(l))
	return n
}

func (m *MsgStreamSendResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *MsgStopStream) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.StreamId)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.Sender)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	return n
}

func (m *MsgStopStreamResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *MsgClaimStreamedAmount) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.StreamId)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.Claimer)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	return n
}

func (m *MsgClaimStreamedAmountResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func sovTx(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozTx(x uint64) (n int) {
	return sovTx(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *MsgStreamSend) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgStreamSend: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgStreamSend: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Sender", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Sender = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Recipient", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Recipient = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Amount", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Amount.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Duration", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := github_com_gogo_protobuf_types.StdDurationUnmarshal(&m.Duration, dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field StreamType", wireType)
			}
			m.StreamType = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.StreamType |= StreamType(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Periods", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Periods = append(m.Periods, &Period{})
			if err := m.Periods[len(m.Periods)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 7:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Cancellable", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.Cancellable = bool(v != 0)
		case 8:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Fee", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Fee.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgStreamSendResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgStreamSendResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgStreamSendResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgStopStream) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgStopStream: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgStopStream: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field StreamId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.StreamId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Sender", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Sender = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgStopStreamResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgStopStreamResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgStopStreamResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgClaimStreamedAmount) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgClaimStreamedAmount: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgClaimStreamedAmount: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field StreamId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.StreamId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Claimer", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Claimer = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgClaimStreamedAmountResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgClaimStreamedAmountResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgClaimStreamedAmountResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipTx(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowTx
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTx
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTx
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthTx
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupTx
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthTx
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthTx        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowTx          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupTx = fmt.Errorf("proto: unexpected end of group")
)
