// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: paymentstream/paymentstream.proto

package types

import (
	fmt "fmt"
	types "github.com/cosmos/cosmos-sdk/types"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	github_com_gogo_protobuf_types "github.com/gogo/protobuf/types"
	_ "google.golang.org/protobuf/types/known/timestamppb"
	io "io"
	math "math"
	math_bits "math/bits"
	time "time"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf
var _ = time.Kitchen

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type PaymentType int32

const (
	TypeDelayed    PaymentType = 0
	TypeContinuous PaymentType = 1
	TypePeriodic   PaymentType = 2
)

var PaymentType_name = map[int32]string{
	0: "PAYMENT_TYPE_DELAYED",
	1: "PAYMENT_TYPE_CONTINUOUS",
	2: "PAYMENT_TYPE_PERIODIC",
}

var PaymentType_value = map[string]int32{
	"PAYMENT_TYPE_DELAYED":    0,
	"PAYMENT_TYPE_CONTINUOUS": 1,
	"PAYMENT_TYPE_PERIODIC":   2,
}

func (x PaymentType) String() string {
	return proto.EnumName(PaymentType_name, int32(x))
}

func (PaymentType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_dc0eb37721adb3e8, []int{0}
}

type PaymentStatus int32

const (
	StatusOpen      PaymentStatus = 0
	StatusCompleted PaymentStatus = 1
	StatusCancelled PaymentStatus = 2
)

var PaymentStatus_name = map[int32]string{
	0: "PAYMENT_STATUS_OPEN",
	1: "PAYMENT_STATUS_COMPLETED",
	2: "PAYMENT_STATUS_CANCELLED",
}

var PaymentStatus_value = map[string]int32{
	"PAYMENT_STATUS_OPEN":      0,
	"PAYMENT_STATUS_COMPLETED": 1,
	"PAYMENT_STATUS_CANCELLED": 2,
}

func (x PaymentStatus) String() string {
	return proto.EnumName(PaymentStatus_name, int32(x))
}

func (PaymentStatus) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_dc0eb37721adb3e8, []int{1}
}

type PaymentStream struct {
	Id                string        `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Sender            string        `protobuf:"bytes,2,opt,name=sender,proto3" json:"sender,omitempty"`
	Recipient         string        `protobuf:"bytes,3,opt,name=recipient,proto3" json:"recipient,omitempty"`
	TotalAmount       types.Coin    `protobuf:"bytes,4,opt,name=total_amount,json=totalAmount,proto3,castrepeated=github.com/cosmos/cosmos-sdk/types.Coin" json:"total_amount" yaml:"total_amount"`
	StreamType        PaymentType   `protobuf:"varint,5,opt,name=stream_type,json=streamType,proto3,enum=OmniFlix.paymentstream.paymentstream.PaymentType" json:"stream_type,omitempty" yaml:"stream_type"`
	Status            PaymentStatus `protobuf:"varint,6,opt,name=status,proto3,enum=OmniFlix.paymentstream.paymentstream.PaymentStatus" json:"status,omitempty"`
	LockHeight        int64         `protobuf:"varint,7,opt,name=lock_height,json=lockHeight,proto3" json:"lock_height,omitempty" yaml:"lock_height"`
	StartTime         time.Time     `protobuf:"bytes,8,opt,name=start_time,json=startTime,proto3,stdtime" json:"start_time" yaml:"start_time"`
	EndTime           time.Time     `protobuf:"bytes,9,opt,name=end_time,json=endTime,proto3,stdtime" json:"end_time" yaml:"end_time"`
	TotalTransferred  types.Coin    `protobuf:"bytes,10,opt,name=total_transferred,json=totalTransferred,proto3,castrepeated=github.com/cosmos/cosmos-sdk/types.Coin" json:"total_transferred" yaml:"total_transferred"`
	LastTransferredAt time.Time     `protobuf:"bytes,11,opt,name=last_transferred_at,json=lastTransferredAt,proto3,stdtime" json:"last_transferred_at" yaml:"last_transferred_at"`
}

func (m *PaymentStream) Reset()         { *m = PaymentStream{} }
func (m *PaymentStream) String() string { return proto.CompactTextString(m) }
func (*PaymentStream) ProtoMessage()    {}
func (*PaymentStream) Descriptor() ([]byte, []int) {
	return fileDescriptor_dc0eb37721adb3e8, []int{0}
}
func (m *PaymentStream) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *PaymentStream) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_PaymentStream.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *PaymentStream) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PaymentStream.Merge(m, src)
}
func (m *PaymentStream) XXX_Size() int {
	return m.Size()
}
func (m *PaymentStream) XXX_DiscardUnknown() {
	xxx_messageInfo_PaymentStream.DiscardUnknown(m)
}

var xxx_messageInfo_PaymentStream proto.InternalMessageInfo

func (m *PaymentStream) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *PaymentStream) GetSender() string {
	if m != nil {
		return m.Sender
	}
	return ""
}

func (m *PaymentStream) GetRecipient() string {
	if m != nil {
		return m.Recipient
	}
	return ""
}

func (m *PaymentStream) GetTotalAmount() types.Coin {
	if m != nil {
		return m.TotalAmount
	}
	return types.Coin{}
}

func (m *PaymentStream) GetStreamType() PaymentType {
	if m != nil {
		return m.StreamType
	}
	return TypeDelayed
}

func (m *PaymentStream) GetStatus() PaymentStatus {
	if m != nil {
		return m.Status
	}
	return StatusOpen
}

func (m *PaymentStream) GetLockHeight() int64 {
	if m != nil {
		return m.LockHeight
	}
	return 0
}

func (m *PaymentStream) GetStartTime() time.Time {
	if m != nil {
		return m.StartTime
	}
	return time.Time{}
}

func (m *PaymentStream) GetEndTime() time.Time {
	if m != nil {
		return m.EndTime
	}
	return time.Time{}
}

func (m *PaymentStream) GetTotalTransferred() types.Coin {
	if m != nil {
		return m.TotalTransferred
	}
	return types.Coin{}
}

func (m *PaymentStream) GetLastTransferredAt() time.Time {
	if m != nil {
		return m.LastTransferredAt
	}
	return time.Time{}
}

func init() {
	proto.RegisterEnum("OmniFlix.paymentstream.paymentstream.PaymentType", PaymentType_name, PaymentType_value)
	proto.RegisterEnum("OmniFlix.paymentstream.paymentstream.PaymentStatus", PaymentStatus_name, PaymentStatus_value)
	proto.RegisterType((*PaymentStream)(nil), "OmniFlix.paymentstream.paymentstream.PaymentStream")
}

func init() { proto.RegisterFile("paymentstream/paymentstream.proto", fileDescriptor_dc0eb37721adb3e8) }

var fileDescriptor_dc0eb37721adb3e8 = []byte{
	// 768 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x54, 0xcd, 0x6e, 0xf3, 0x44,
	0x14, 0x8d, 0xf3, 0x7d, 0xa4, 0xcd, 0xa4, 0xa4, 0xee, 0xa4, 0x14, 0x63, 0xc0, 0x31, 0x11, 0xa2,
	0xa1, 0xa8, 0xb6, 0xd2, 0x2e, 0x40, 0xec, 0xf2, 0xe3, 0x8a, 0xaa, 0x69, 0x12, 0x39, 0xae, 0x44,
	0xd9, 0x58, 0x4e, 0x3c, 0x4d, 0x4d, 0x6d, 0x8f, 0x65, 0x4f, 0x50, 0xb3, 0x47, 0x08, 0x65, 0x55,
	0x89, 0x2d, 0x59, 0xc1, 0x8a, 0x27, 0xe9, 0xb2, 0x4b, 0x56, 0x2d, 0x6a, 0xdf, 0xa0, 0x4f, 0x80,
	0x3c, 0x63, 0xab, 0x4e, 0x41, 0xea, 0xd7, 0x55, 0x7c, 0x67, 0xce, 0x39, 0x77, 0xee, 0xbd, 0x27,
	0x17, 0x7c, 0x16, 0x58, 0x33, 0x0f, 0xf9, 0x24, 0x22, 0x21, 0xb2, 0x3c, 0x75, 0x29, 0x52, 0x82,
	0x10, 0x13, 0x0c, 0x3f, 0xef, 0x7b, 0xbe, 0x73, 0xe0, 0x3a, 0x97, 0xca, 0xb3, 0xdb, 0x6c, 0x24,
	0x4a, 0x63, 0x1c, 0x79, 0x38, 0x52, 0x47, 0x56, 0x84, 0xd4, 0x9f, 0x1a, 0x23, 0x44, 0xac, 0x86,
	0x3a, 0xc6, 0x8e, 0xcf, 0x54, 0xc4, 0xcd, 0x09, 0x9e, 0x60, 0xfa, 0xa9, 0xc6, 0x5f, 0xc9, 0x69,
	0x75, 0x82, 0xf1, 0xc4, 0x45, 0x2a, 0x8d, 0x46, 0xd3, 0x33, 0x95, 0x38, 0x1e, 0x8a, 0x88, 0xe5,
	0x05, 0x0c, 0x50, 0xfb, 0x65, 0x05, 0xbc, 0x3f, 0x60, 0x89, 0x86, 0x34, 0x11, 0x2c, 0x83, 0xbc,
	0x63, 0x0b, 0x9c, 0xcc, 0xd5, 0x8b, 0x7a, 0xde, 0xb1, 0xe1, 0x16, 0x28, 0x44, 0xc8, 0xb7, 0x51,
	0x28, 0xe4, 0xe9, 0x59, 0x12, 0xc1, 0x4f, 0x40, 0x31, 0x44, 0x63, 0x27, 0x70, 0x90, 0x4f, 0x84,
	0x37, 0xf4, 0xea, 0xe9, 0x00, 0xfe, 0xcc, 0x81, 0x35, 0x82, 0x89, 0xe5, 0x9a, 0x96, 0x87, 0xa7,
	0x3e, 0x11, 0xde, 0xca, 0x5c, 0xbd, 0xb4, 0xf7, 0x91, 0xc2, 0xca, 0x50, 0xe2, 0x32, 0x94, 0xa4,
	0x0c, 0xa5, 0x8d, 0x1d, 0xbf, 0x75, 0x70, 0x7d, 0x5b, 0xcd, 0x3d, 0xde, 0x56, 0x2b, 0x33, 0xcb,
	0x73, 0xbf, 0xad, 0x65, 0xc9, 0xb5, 0xbf, 0xee, 0xaa, 0xdb, 0x13, 0x87, 0x9c, 0x4f, 0x47, 0xca,
	0x18, 0x7b, 0x6a, 0xd2, 0x0a, 0xf6, 0xb3, 0x1b, 0xd9, 0x17, 0x2a, 0x99, 0x05, 0x28, 0xa2, 0x3a,
	0x7a, 0x89, 0x32, 0x9b, 0x94, 0x08, 0x7f, 0x04, 0x25, 0xd6, 0x3f, 0x33, 0x46, 0x08, 0xef, 0xc9,
	0x5c, 0xbd, 0xbc, 0xd7, 0x50, 0xde, 0xa5, 0xe3, 0x4a, 0xd2, 0x16, 0x63, 0x16, 0xa0, 0xd6, 0xd6,
	0xe3, 0x6d, 0x15, 0xb2, 0x87, 0x65, 0xf4, 0x6a, 0x3a, 0x60, 0x51, 0x8c, 0x81, 0x47, 0xa0, 0x10,
	0x11, 0x8b, 0x4c, 0x23, 0xa1, 0x40, 0xd3, 0xec, 0xbf, 0x2a, 0xcd, 0x90, 0x52, 0xf5, 0x44, 0x02,
	0x7e, 0x0d, 0x4a, 0x2e, 0x1e, 0x5f, 0x98, 0xe7, 0xc8, 0x99, 0x9c, 0x13, 0x61, 0x45, 0xe6, 0xea,
	0x6f, 0xb2, 0xaf, 0xc8, 0x5c, 0xd6, 0x74, 0x10, 0x47, 0xdf, 0xd1, 0x00, 0x7e, 0x0f, 0x40, 0x44,
	0xac, 0x90, 0x98, 0xf1, 0xa4, 0x85, 0x55, 0xda, 0x75, 0x51, 0x61, 0x36, 0x50, 0x52, 0x1b, 0x28,
	0x46, 0x6a, 0x83, 0xd6, 0xa7, 0x49, 0xdb, 0x37, 0xd2, 0xea, 0x52, 0x6e, 0xed, 0xea, 0xae, 0xca,
	0xe9, 0x45, 0x7a, 0x10, 0xc3, 0xa1, 0x0e, 0x56, 0x91, 0x6f, 0x33, 0xdd, 0xe2, 0x8b, 0xba, 0x1f,
	0x27, 0xba, 0xeb, 0x4c, 0x37, 0x65, 0x32, 0xd5, 0x15, 0xe4, 0xdb, 0x54, 0xf3, 0x37, 0x0e, 0x6c,
	0xb0, 0x49, 0x93, 0xd0, 0xf2, 0xa3, 0x33, 0x14, 0x86, 0xc8, 0x16, 0xc0, 0x4b, 0x5e, 0x39, 0x4a,
	0xc4, 0x85, 0xac, 0x57, 0x32, 0x0a, 0xaf, 0x32, 0x0c, 0x4f, 0xe9, 0xc6, 0x13, 0x1b, 0x86, 0xa0,
	0xe2, 0x5a, 0x11, 0xc9, 0x2a, 0x9a, 0x16, 0x11, 0x4a, 0x2f, 0x16, 0xfd, 0x45, 0xf2, 0x2e, 0x31,
	0x19, 0xd2, 0x7f, 0x45, 0x58, 0xfd, 0x1b, 0xf1, 0x4d, 0x26, 0x63, 0x93, 0xec, 0xfc, 0xce, 0x81,
	0x52, 0xc6, 0x71, 0xf0, 0x4b, 0xb0, 0x39, 0x68, 0x9e, 0x1e, 0x6b, 0x3d, 0xc3, 0x34, 0x4e, 0x07,
	0x9a, 0xd9, 0xd1, 0xba, 0xcd, 0x53, 0xad, 0xc3, 0xe7, 0xc4, 0xf5, 0xf9, 0x42, 0x2e, 0xc5, 0x98,
	0x0e, 0x72, 0xad, 0x19, 0xb2, 0xa1, 0x0a, 0x3e, 0x5c, 0x82, 0xb6, 0xfb, 0x3d, 0xe3, 0xb0, 0x77,
	0xd2, 0x3f, 0x19, 0xf2, 0x9c, 0x08, 0xe7, 0x0b, 0xb9, 0x1c, 0xa3, 0xdb, 0xd8, 0x27, 0x8e, 0x3f,
	0xc5, 0xd3, 0x08, 0x7e, 0x05, 0x3e, 0x58, 0x22, 0x0c, 0x34, 0xfd, 0xb0, 0xdf, 0x39, 0x6c, 0xf3,
	0x79, 0x91, 0x9f, 0x2f, 0xe4, 0xb5, 0x18, 0x3e, 0x40, 0xa1, 0x83, 0x6d, 0x67, 0x2c, 0xbe, 0xfd,
	0xf5, 0x0f, 0x29, 0xb7, 0xf3, 0x27, 0x97, 0xd9, 0x13, 0xd4, 0xa1, 0xdb, 0xa0, 0x92, 0x8a, 0x0c,
	0x8d, 0xa6, 0x71, 0x32, 0x34, 0xfb, 0x03, 0xad, 0xc7, 0xe7, 0xc4, 0xf2, 0x7c, 0x21, 0x03, 0x06,
	0xea, 0x07, 0xc8, 0x87, 0x0d, 0x20, 0x3c, 0x03, 0xb6, 0xfb, 0xc7, 0x83, 0xae, 0x66, 0x68, 0x1d,
	0x9e, 0x13, 0x2b, 0xf3, 0x85, 0xbc, 0xce, 0xd0, 0x6d, 0xec, 0x05, 0x2e, 0x22, 0xc8, 0xfe, 0x3f,
	0x4a, 0xb3, 0xd7, 0xd6, 0xba, 0x5d, 0xad, 0xc3, 0xe7, 0x97, 0x28, 0x96, 0x3f, 0x46, 0xae, 0x8b,
	0x6c, 0xf6, 0xcc, 0x96, 0x7e, 0x7d, 0x2f, 0x71, 0x37, 0xf7, 0x12, 0xf7, 0xcf, 0xbd, 0xc4, 0x5d,
	0x3d, 0x48, 0xb9, 0x9b, 0x07, 0x29, 0xf7, 0xf7, 0x83, 0x94, 0xfb, 0xe1, 0x9b, 0x8c, 0x1d, 0xd2,
	0xff, 0x65, 0xba, 0x8e, 0x77, 0x93, 0xed, 0x7c, 0xb9, 0xbc, 0x9f, 0x99, 0x49, 0x46, 0x05, 0x3a,
	0xe8, 0xfd, 0x7f, 0x03, 0x00, 0x00, 0xff, 0xff, 0xd7, 0x63, 0xe0, 0xee, 0xcb, 0x05, 0x00, 0x00,
}

func (m *PaymentStream) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *PaymentStream) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *PaymentStream) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	n1, err1 := github_com_gogo_protobuf_types.StdTimeMarshalTo(m.LastTransferredAt, dAtA[i-github_com_gogo_protobuf_types.SizeOfStdTime(m.LastTransferredAt):])
	if err1 != nil {
		return 0, err1
	}
	i -= n1
	i = encodeVarintPaymentstream(dAtA, i, uint64(n1))
	i--
	dAtA[i] = 0x5a
	{
		size, err := m.TotalTransferred.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintPaymentstream(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x52
	n3, err3 := github_com_gogo_protobuf_types.StdTimeMarshalTo(m.EndTime, dAtA[i-github_com_gogo_protobuf_types.SizeOfStdTime(m.EndTime):])
	if err3 != nil {
		return 0, err3
	}
	i -= n3
	i = encodeVarintPaymentstream(dAtA, i, uint64(n3))
	i--
	dAtA[i] = 0x4a
	n4, err4 := github_com_gogo_protobuf_types.StdTimeMarshalTo(m.StartTime, dAtA[i-github_com_gogo_protobuf_types.SizeOfStdTime(m.StartTime):])
	if err4 != nil {
		return 0, err4
	}
	i -= n4
	i = encodeVarintPaymentstream(dAtA, i, uint64(n4))
	i--
	dAtA[i] = 0x42
	if m.LockHeight != 0 {
		i = encodeVarintPaymentstream(dAtA, i, uint64(m.LockHeight))
		i--
		dAtA[i] = 0x38
	}
	if m.Status != 0 {
		i = encodeVarintPaymentstream(dAtA, i, uint64(m.Status))
		i--
		dAtA[i] = 0x30
	}
	if m.StreamType != 0 {
		i = encodeVarintPaymentstream(dAtA, i, uint64(m.StreamType))
		i--
		dAtA[i] = 0x28
	}
	{
		size, err := m.TotalAmount.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintPaymentstream(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x22
	if len(m.Recipient) > 0 {
		i -= len(m.Recipient)
		copy(dAtA[i:], m.Recipient)
		i = encodeVarintPaymentstream(dAtA, i, uint64(len(m.Recipient)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.Sender) > 0 {
		i -= len(m.Sender)
		copy(dAtA[i:], m.Sender)
		i = encodeVarintPaymentstream(dAtA, i, uint64(len(m.Sender)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Id) > 0 {
		i -= len(m.Id)
		copy(dAtA[i:], m.Id)
		i = encodeVarintPaymentstream(dAtA, i, uint64(len(m.Id)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintPaymentstream(dAtA []byte, offset int, v uint64) int {
	offset -= sovPaymentstream(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *PaymentStream) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Id)
	if l > 0 {
		n += 1 + l + sovPaymentstream(uint64(l))
	}
	l = len(m.Sender)
	if l > 0 {
		n += 1 + l + sovPaymentstream(uint64(l))
	}
	l = len(m.Recipient)
	if l > 0 {
		n += 1 + l + sovPaymentstream(uint64(l))
	}
	l = m.TotalAmount.Size()
	n += 1 + l + sovPaymentstream(uint64(l))
	if m.StreamType != 0 {
		n += 1 + sovPaymentstream(uint64(m.StreamType))
	}
	if m.Status != 0 {
		n += 1 + sovPaymentstream(uint64(m.Status))
	}
	if m.LockHeight != 0 {
		n += 1 + sovPaymentstream(uint64(m.LockHeight))
	}
	l = github_com_gogo_protobuf_types.SizeOfStdTime(m.StartTime)
	n += 1 + l + sovPaymentstream(uint64(l))
	l = github_com_gogo_protobuf_types.SizeOfStdTime(m.EndTime)
	n += 1 + l + sovPaymentstream(uint64(l))
	l = m.TotalTransferred.Size()
	n += 1 + l + sovPaymentstream(uint64(l))
	l = github_com_gogo_protobuf_types.SizeOfStdTime(m.LastTransferredAt)
	n += 1 + l + sovPaymentstream(uint64(l))
	return n
}

func sovPaymentstream(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozPaymentstream(x uint64) (n int) {
	return sovPaymentstream(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *PaymentStream) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowPaymentstream
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: PaymentStream: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: PaymentStream: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPaymentstream
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthPaymentstream
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthPaymentstream
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Id = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Sender", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPaymentstream
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthPaymentstream
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthPaymentstream
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Sender = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Recipient", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPaymentstream
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthPaymentstream
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthPaymentstream
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Recipient = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TotalAmount", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPaymentstream
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthPaymentstream
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthPaymentstream
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.TotalAmount.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field StreamType", wireType)
			}
			m.StreamType = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPaymentstream
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.StreamType |= PaymentType(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 6:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Status", wireType)
			}
			m.Status = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPaymentstream
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Status |= PaymentStatus(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 7:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field LockHeight", wireType)
			}
			m.LockHeight = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPaymentstream
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.LockHeight |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 8:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field StartTime", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPaymentstream
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthPaymentstream
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthPaymentstream
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := github_com_gogo_protobuf_types.StdTimeUnmarshal(&m.StartTime, dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 9:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field EndTime", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPaymentstream
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthPaymentstream
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthPaymentstream
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := github_com_gogo_protobuf_types.StdTimeUnmarshal(&m.EndTime, dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 10:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TotalTransferred", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPaymentstream
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthPaymentstream
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthPaymentstream
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.TotalTransferred.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 11:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field LastTransferredAt", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPaymentstream
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthPaymentstream
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthPaymentstream
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := github_com_gogo_protobuf_types.StdTimeUnmarshal(&m.LastTransferredAt, dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipPaymentstream(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthPaymentstream
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipPaymentstream(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowPaymentstream
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowPaymentstream
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowPaymentstream
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthPaymentstream
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupPaymentstream
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthPaymentstream
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthPaymentstream        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowPaymentstream          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupPaymentstream = fmt.Errorf("proto: unexpected end of group")
)
