// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: paymentstream/query.proto

package types

import (
	context "context"
	fmt "fmt"
	query "github.com/cosmos/cosmos-sdk/types/query"
	_ "github.com/gogo/protobuf/gogoproto"
	grpc1 "github.com/gogo/protobuf/grpc"
	proto "github.com/gogo/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type QueryAllPaymentStreamRequest struct {
	Pagination *query.PageRequest `protobuf:"bytes,1,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QueryAllPaymentStreamRequest) Reset()         { *m = QueryAllPaymentStreamRequest{} }
func (m *QueryAllPaymentStreamRequest) String() string { return proto.CompactTextString(m) }
func (*QueryAllPaymentStreamRequest) ProtoMessage()    {}
func (*QueryAllPaymentStreamRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_5fa2c1661fb88ff7, []int{0}
}
func (m *QueryAllPaymentStreamRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryAllPaymentStreamRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryAllPaymentStreamRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryAllPaymentStreamRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryAllPaymentStreamRequest.Merge(m, src)
}
func (m *QueryAllPaymentStreamRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryAllPaymentStreamRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryAllPaymentStreamRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryAllPaymentStreamRequest proto.InternalMessageInfo

func (m *QueryAllPaymentStreamRequest) GetPagination() *query.PageRequest {
	if m != nil {
		return m.Pagination
	}
	return nil
}

type QueryAllPaymentStreamResponse struct {
	PaymentStreams []PaymentStream     `protobuf:"bytes,1,rep,name=payment_streams,json=paymentStreams,proto3" json:"payment_streams" yaml:"payment_streams"`
	Pagination     *query.PageResponse `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QueryAllPaymentStreamResponse) Reset()         { *m = QueryAllPaymentStreamResponse{} }
func (m *QueryAllPaymentStreamResponse) String() string { return proto.CompactTextString(m) }
func (*QueryAllPaymentStreamResponse) ProtoMessage()    {}
func (*QueryAllPaymentStreamResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_5fa2c1661fb88ff7, []int{1}
}
func (m *QueryAllPaymentStreamResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryAllPaymentStreamResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryAllPaymentStreamResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryAllPaymentStreamResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryAllPaymentStreamResponse.Merge(m, src)
}
func (m *QueryAllPaymentStreamResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryAllPaymentStreamResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryAllPaymentStreamResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryAllPaymentStreamResponse proto.InternalMessageInfo

func (m *QueryAllPaymentStreamResponse) GetPaymentStreams() []PaymentStream {
	if m != nil {
		return m.PaymentStreams
	}
	return nil
}

func (m *QueryAllPaymentStreamResponse) GetPagination() *query.PageResponse {
	if m != nil {
		return m.Pagination
	}
	return nil
}

type QueryPaymentStreamsRequest struct {
	Status     string             `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Pagination *query.PageRequest `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QueryPaymentStreamsRequest) Reset()         { *m = QueryPaymentStreamsRequest{} }
func (m *QueryPaymentStreamsRequest) String() string { return proto.CompactTextString(m) }
func (*QueryPaymentStreamsRequest) ProtoMessage()    {}
func (*QueryPaymentStreamsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_5fa2c1661fb88ff7, []int{2}
}
func (m *QueryPaymentStreamsRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryPaymentStreamsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryPaymentStreamsRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryPaymentStreamsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryPaymentStreamsRequest.Merge(m, src)
}
func (m *QueryPaymentStreamsRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryPaymentStreamsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryPaymentStreamsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryPaymentStreamsRequest proto.InternalMessageInfo

func (m *QueryPaymentStreamsRequest) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *QueryPaymentStreamsRequest) GetPagination() *query.PageRequest {
	if m != nil {
		return m.Pagination
	}
	return nil
}

type QueryPaymentStreamsResponse struct {
	PaymentStreams []PaymentStream     `protobuf:"bytes,1,rep,name=payment_streams,json=paymentStreams,proto3" json:"payment_streams" yaml:"payment_streams"`
	Pagination     *query.PageResponse `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QueryPaymentStreamsResponse) Reset()         { *m = QueryPaymentStreamsResponse{} }
func (m *QueryPaymentStreamsResponse) String() string { return proto.CompactTextString(m) }
func (*QueryPaymentStreamsResponse) ProtoMessage()    {}
func (*QueryPaymentStreamsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_5fa2c1661fb88ff7, []int{3}
}
func (m *QueryPaymentStreamsResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryPaymentStreamsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryPaymentStreamsResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryPaymentStreamsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryPaymentStreamsResponse.Merge(m, src)
}
func (m *QueryPaymentStreamsResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryPaymentStreamsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryPaymentStreamsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryPaymentStreamsResponse proto.InternalMessageInfo

func (m *QueryPaymentStreamsResponse) GetPaymentStreams() []PaymentStream {
	if m != nil {
		return m.PaymentStreams
	}
	return nil
}

func (m *QueryPaymentStreamsResponse) GetPagination() *query.PageResponse {
	if m != nil {
		return m.Pagination
	}
	return nil
}

type QuerySenderPaymentStreamsRequest struct {
	Sender     string             `protobuf:"bytes,1,opt,name=sender,proto3" json:"sender,omitempty"`
	Pagination *query.PageRequest `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QuerySenderPaymentStreamsRequest) Reset()         { *m = QuerySenderPaymentStreamsRequest{} }
func (m *QuerySenderPaymentStreamsRequest) String() string { return proto.CompactTextString(m) }
func (*QuerySenderPaymentStreamsRequest) ProtoMessage()    {}
func (*QuerySenderPaymentStreamsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_5fa2c1661fb88ff7, []int{4}
}
func (m *QuerySenderPaymentStreamsRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QuerySenderPaymentStreamsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QuerySenderPaymentStreamsRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QuerySenderPaymentStreamsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QuerySenderPaymentStreamsRequest.Merge(m, src)
}
func (m *QuerySenderPaymentStreamsRequest) XXX_Size() int {
	return m.Size()
}
func (m *QuerySenderPaymentStreamsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QuerySenderPaymentStreamsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QuerySenderPaymentStreamsRequest proto.InternalMessageInfo

func (m *QuerySenderPaymentStreamsRequest) GetSender() string {
	if m != nil {
		return m.Sender
	}
	return ""
}

func (m *QuerySenderPaymentStreamsRequest) GetPagination() *query.PageRequest {
	if m != nil {
		return m.Pagination
	}
	return nil
}

type QueryRecipientPaymentStreamsRequest struct {
	Recipient  string             `protobuf:"bytes,1,opt,name=recipient,proto3" json:"recipient,omitempty"`
	Pagination *query.PageRequest `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QueryRecipientPaymentStreamsRequest) Reset()         { *m = QueryRecipientPaymentStreamsRequest{} }
func (m *QueryRecipientPaymentStreamsRequest) String() string { return proto.CompactTextString(m) }
func (*QueryRecipientPaymentStreamsRequest) ProtoMessage()    {}
func (*QueryRecipientPaymentStreamsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_5fa2c1661fb88ff7, []int{5}
}
func (m *QueryRecipientPaymentStreamsRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryRecipientPaymentStreamsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryRecipientPaymentStreamsRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryRecipientPaymentStreamsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryRecipientPaymentStreamsRequest.Merge(m, src)
}
func (m *QueryRecipientPaymentStreamsRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryRecipientPaymentStreamsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryRecipientPaymentStreamsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryRecipientPaymentStreamsRequest proto.InternalMessageInfo

func (m *QueryRecipientPaymentStreamsRequest) GetRecipient() string {
	if m != nil {
		return m.Recipient
	}
	return ""
}

func (m *QueryRecipientPaymentStreamsRequest) GetPagination() *query.PageRequest {
	if m != nil {
		return m.Pagination
	}
	return nil
}

func init() {
	proto.RegisterType((*QueryAllPaymentStreamRequest)(nil), "OmniFlix.paymentstream.paymentstream.QueryAllPaymentStreamRequest")
	proto.RegisterType((*QueryAllPaymentStreamResponse)(nil), "OmniFlix.paymentstream.paymentstream.QueryAllPaymentStreamResponse")
	proto.RegisterType((*QueryPaymentStreamsRequest)(nil), "OmniFlix.paymentstream.paymentstream.QueryPaymentStreamsRequest")
	proto.RegisterType((*QueryPaymentStreamsResponse)(nil), "OmniFlix.paymentstream.paymentstream.QueryPaymentStreamsResponse")
	proto.RegisterType((*QuerySenderPaymentStreamsRequest)(nil), "OmniFlix.paymentstream.paymentstream.QuerySenderPaymentStreamsRequest")
	proto.RegisterType((*QueryRecipientPaymentStreamsRequest)(nil), "OmniFlix.paymentstream.paymentstream.QueryRecipientPaymentStreamsRequest")
}

func init() { proto.RegisterFile("paymentstream/query.proto", fileDescriptor_5fa2c1661fb88ff7) }

var fileDescriptor_5fa2c1661fb88ff7 = []byte{
	// 588 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xdc, 0x95, 0x4f, 0x6f, 0x12, 0x41,
	0x18, 0xc6, 0x19, 0x8c, 0x24, 0x9d, 0x26, 0x35, 0x8e, 0xb5, 0x7f, 0x28, 0x5d, 0x28, 0xfe, 0x69,
	0x63, 0xc2, 0x4e, 0x4a, 0x2f, 0xc6, 0x93, 0x60, 0x82, 0xf1, 0x64, 0xdd, 0xde, 0xbc, 0x98, 0x01,
	0xc7, 0x75, 0x92, 0xdd, 0x99, 0x2d, 0x33, 0x98, 0x12, 0xdb, 0x4b, 0xaf, 0x5e, 0x4c, 0xbc, 0xf9,
	0x31, 0xbc, 0x7b, 0xe7, 0x48, 0xe2, 0xc5, 0x53, 0x63, 0xa0, 0xf1, 0x03, 0xf8, 0x09, 0x0c, 0x33,
	0x0b, 0x74, 0x08, 0x60, 0xb1, 0x9c, 0x7a, 0xdb, 0x5d, 0xde, 0xf7, 0x79, 0x7f, 0xcf, 0x33, 0x33,
	0x0c, 0x5c, 0x8f, 0x48, 0x33, 0xa4, 0x5c, 0x49, 0x55, 0xa7, 0x24, 0xc4, 0x87, 0x0d, 0x5a, 0x6f,
	0xba, 0x51, 0x5d, 0x28, 0x81, 0xee, 0xbf, 0x0c, 0x39, 0xab, 0x04, 0xec, 0xc8, 0xb5, 0x6a, 0xec,
	0xb7, 0x74, 0xc6, 0x17, 0xc2, 0x0f, 0x28, 0x26, 0x11, 0xc3, 0x84, 0x73, 0xa1, 0x88, 0x62, 0x82,
	0x4b, 0xa3, 0x91, 0x7e, 0x54, 0x13, 0x32, 0x14, 0x12, 0x57, 0x89, 0xa4, 0x46, 0x1c, 0x7f, 0xd8,
	0xad, 0x52, 0x45, 0x76, 0x71, 0x44, 0x7c, 0xc6, 0x75, 0x71, 0x5c, 0xbb, 0x65, 0xa3, 0x8c, 0x0c,
	0xd5, 0x25, 0xcb, 0xbe, 0xf0, 0x85, 0x7e, 0xc4, 0xbd, 0x27, 0xf3, 0x35, 0xff, 0x0e, 0x66, 0x5e,
	0xf5, 0xa4, 0x4b, 0x41, 0xb0, 0x6f, 0x9a, 0x0e, 0x74, 0x93, 0x47, 0x0f, 0x1b, 0x54, 0x2a, 0x54,
	0x81, 0x70, 0x38, 0x6c, 0x0d, 0xe4, 0xc0, 0xce, 0x62, 0xf1, 0xa1, 0x6b, 0xc8, 0xdc, 0x1e, 0x99,
	0x6b, 0x6c, 0xc7, 0x64, 0xee, 0x3e, 0xf1, 0x69, 0xdc, 0xeb, 0x5d, 0xe8, 0xcc, 0xff, 0x06, 0x70,
	0x73, 0xc2, 0x20, 0x19, 0x09, 0x2e, 0x29, 0x3a, 0x86, 0xb7, 0x62, 0xec, 0x37, 0x86, 0x5b, 0xae,
	0x81, 0xdc, 0x8d, 0x9d, 0xc5, 0xe2, 0x9e, 0x7b, 0x99, 0x30, 0x5d, 0x4b, 0xb5, 0xec, 0xb4, 0xce,
	0xb2, 0x89, 0x3f, 0x67, 0xd9, 0x95, 0x26, 0x09, 0x83, 0x27, 0xf9, 0x11, 0xe5, 0xbc, 0xb7, 0x14,
	0x5d, 0x2c, 0x97, 0xe8, 0xb9, 0xe5, 0x33, 0xa9, 0x7d, 0x6e, 0xff, 0xd3, 0xa7, 0x41, 0xb7, 0x8c,
	0x1e, 0xc3, 0xb4, 0xf6, 0x69, 0xe1, 0xc8, 0x7e, 0x9c, 0x2b, 0x30, 0x25, 0x15, 0x51, 0x0d, 0xa9,
	0xa3, 0x5c, 0xf0, 0xe2, 0xb7, 0x91, 0x98, 0x93, 0xff, 0x1d, 0xf3, 0x39, 0x80, 0x1b, 0x63, 0xc7,
	0x5f, 0xaf, 0x90, 0x4f, 0x01, 0xcc, 0x69, 0x9b, 0x07, 0x94, 0xbf, 0xa5, 0xf5, 0xc9, 0x59, 0xeb,
	0x9f, 0x07, 0x59, 0xeb, 0xb7, 0xb9, 0x65, 0xfd, 0x09, 0xc0, 0x7b, 0x1a, 0xc2, 0xa3, 0x35, 0x16,
	0x31, 0xca, 0xd5, 0x78, 0x8e, 0x0c, 0x5c, 0xa8, 0xf7, 0x2b, 0x62, 0x94, 0xe1, 0x87, 0x79, 0xd1,
	0x14, 0xbf, 0xa6, 0xe0, 0x4d, 0x4d, 0x83, 0xbe, 0x03, 0x78, 0xdb, 0x26, 0x29, 0x05, 0x01, 0x2a,
	0x5f, 0x6e, 0x81, 0xa7, 0xfd, 0x19, 0xa4, 0x9f, 0x5d, 0x49, 0xc3, 0xac, 0x63, 0x3e, 0x7b, 0xfa,
	0xe3, 0xfc, 0x4b, 0x72, 0x1d, 0xad, 0x62, 0x12, 0x04, 0x05, 0xd3, 0xc2, 0xb8, 0x5f, 0xe8, 0x6b,
	0xa0, 0x6f, 0x00, 0x2e, 0xd9, 0xfc, 0xe8, 0xe9, 0x0c, 0x83, 0xc7, 0x2e, 0x42, 0xba, 0x74, 0x05,
	0x85, 0x18, 0x7c, 0x43, 0x83, 0xdf, 0x45, 0x77, 0xf0, 0x18, 0xe8, 0x16, 0x80, 0xcb, 0xe3, 0x36,
	0x23, 0xaa, 0xcc, 0x30, 0x78, 0xca, 0x6e, 0x9e, 0x87, 0x81, 0x07, 0xda, 0x40, 0x16, 0x6d, 0xf6,
	0xef, 0x87, 0x82, 0x68, 0xa8, 0x78, 0x05, 0x24, 0xfe, 0x68, 0x8e, 0xc7, 0x09, 0x6a, 0x03, 0xb8,
	0x3a, 0x61, 0x4b, 0xa3, 0x17, 0x33, 0x50, 0x4c, 0x3f, 0x16, 0xf3, 0x30, 0xb4, 0xad, 0x0d, 0x6d,
	0xa1, 0xec, 0xc0, 0x10, 0xe3, 0x43, 0x3f, 0x83, 0x33, 0x76, 0x52, 0xf6, 0x5a, 0x1d, 0x07, 0xb4,
	0x3b, 0x0e, 0xf8, 0xd5, 0x71, 0xc0, 0xe7, 0xae, 0x93, 0x68, 0x77, 0x9d, 0xc4, 0xcf, 0xae, 0x93,
	0x78, 0xfd, 0xd8, 0x67, 0xea, 0x7d, 0xa3, 0xea, 0xd6, 0x44, 0x88, 0xfb, 0x3c, 0x03, 0xb5, 0xf8,
	0x36, 0x3d, 0xb2, 0xef, 0x53, 0xac, 0x9a, 0x11, 0x95, 0xd5, 0x94, 0xbe, 0x40, 0xf7, 0xfe, 0x06,
	0x00, 0x00, 0xff, 0xff, 0xdd, 0x85, 0xc9, 0x86, 0x06, 0x08, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// QueryClient is the client API for Query service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type QueryClient interface {
	PaymentStreamsAll(ctx context.Context, in *QueryAllPaymentStreamRequest, opts ...grpc.CallOption) (*QueryAllPaymentStreamResponse, error)
	PaymentStreams(ctx context.Context, in *QueryPaymentStreamsRequest, opts ...grpc.CallOption) (*QueryPaymentStreamsResponse, error)
	SenderPaymentStreams(ctx context.Context, in *QuerySenderPaymentStreamsRequest, opts ...grpc.CallOption) (*QueryPaymentStreamsResponse, error)
	RecipientPaymentStreams(ctx context.Context, in *QueryRecipientPaymentStreamsRequest, opts ...grpc.CallOption) (*QueryPaymentStreamsResponse, error)
}

type queryClient struct {
	cc grpc1.ClientConn
}

func NewQueryClient(cc grpc1.ClientConn) QueryClient {
	return &queryClient{cc}
}

func (c *queryClient) PaymentStreamsAll(ctx context.Context, in *QueryAllPaymentStreamRequest, opts ...grpc.CallOption) (*QueryAllPaymentStreamResponse, error) {
	out := new(QueryAllPaymentStreamResponse)
	err := c.cc.Invoke(ctx, "/OmniFlix.paymentstream.paymentstream.Query/PaymentStreamsAll", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) PaymentStreams(ctx context.Context, in *QueryPaymentStreamsRequest, opts ...grpc.CallOption) (*QueryPaymentStreamsResponse, error) {
	out := new(QueryPaymentStreamsResponse)
	err := c.cc.Invoke(ctx, "/OmniFlix.paymentstream.paymentstream.Query/PaymentStreams", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) SenderPaymentStreams(ctx context.Context, in *QuerySenderPaymentStreamsRequest, opts ...grpc.CallOption) (*QueryPaymentStreamsResponse, error) {
	out := new(QueryPaymentStreamsResponse)
	err := c.cc.Invoke(ctx, "/OmniFlix.paymentstream.paymentstream.Query/SenderPaymentStreams", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) RecipientPaymentStreams(ctx context.Context, in *QueryRecipientPaymentStreamsRequest, opts ...grpc.CallOption) (*QueryPaymentStreamsResponse, error) {
	out := new(QueryPaymentStreamsResponse)
	err := c.cc.Invoke(ctx, "/OmniFlix.paymentstream.paymentstream.Query/RecipientPaymentStreams", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QueryServer is the server API for Query service.
type QueryServer interface {
	PaymentStreamsAll(context.Context, *QueryAllPaymentStreamRequest) (*QueryAllPaymentStreamResponse, error)
	PaymentStreams(context.Context, *QueryPaymentStreamsRequest) (*QueryPaymentStreamsResponse, error)
	SenderPaymentStreams(context.Context, *QuerySenderPaymentStreamsRequest) (*QueryPaymentStreamsResponse, error)
	RecipientPaymentStreams(context.Context, *QueryRecipientPaymentStreamsRequest) (*QueryPaymentStreamsResponse, error)
}

// UnimplementedQueryServer can be embedded to have forward compatible implementations.
type UnimplementedQueryServer struct {
}

func (*UnimplementedQueryServer) PaymentStreamsAll(ctx context.Context, req *QueryAllPaymentStreamRequest) (*QueryAllPaymentStreamResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PaymentStreamsAll not implemented")
}
func (*UnimplementedQueryServer) PaymentStreams(ctx context.Context, req *QueryPaymentStreamsRequest) (*QueryPaymentStreamsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PaymentStreams not implemented")
}
func (*UnimplementedQueryServer) SenderPaymentStreams(ctx context.Context, req *QuerySenderPaymentStreamsRequest) (*QueryPaymentStreamsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SenderPaymentStreams not implemented")
}
func (*UnimplementedQueryServer) RecipientPaymentStreams(ctx context.Context, req *QueryRecipientPaymentStreamsRequest) (*QueryPaymentStreamsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RecipientPaymentStreams not implemented")
}

func RegisterQueryServer(s grpc1.Server, srv QueryServer) {
	s.RegisterService(&_Query_serviceDesc, srv)
}

func _Query_PaymentStreamsAll_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryAllPaymentStreamRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).PaymentStreamsAll(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/OmniFlix.paymentstream.paymentstream.Query/PaymentStreamsAll",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).PaymentStreamsAll(ctx, req.(*QueryAllPaymentStreamRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_PaymentStreams_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryPaymentStreamsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).PaymentStreams(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/OmniFlix.paymentstream.paymentstream.Query/PaymentStreams",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).PaymentStreams(ctx, req.(*QueryPaymentStreamsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_SenderPaymentStreams_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QuerySenderPaymentStreamsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).SenderPaymentStreams(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/OmniFlix.paymentstream.paymentstream.Query/SenderPaymentStreams",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).SenderPaymentStreams(ctx, req.(*QuerySenderPaymentStreamsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_RecipientPaymentStreams_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryRecipientPaymentStreamsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).RecipientPaymentStreams(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/OmniFlix.paymentstream.paymentstream.Query/RecipientPaymentStreams",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).RecipientPaymentStreams(ctx, req.(*QueryRecipientPaymentStreamsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Query_serviceDesc = grpc.ServiceDesc{
	ServiceName: "OmniFlix.paymentstream.paymentstream.Query",
	HandlerType: (*QueryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "PaymentStreamsAll",
			Handler:    _Query_PaymentStreamsAll_Handler,
		},
		{
			MethodName: "PaymentStreams",
			Handler:    _Query_PaymentStreams_Handler,
		},
		{
			MethodName: "SenderPaymentStreams",
			Handler:    _Query_SenderPaymentStreams_Handler,
		},
		{
			MethodName: "RecipientPaymentStreams",
			Handler:    _Query_RecipientPaymentStreams_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "paymentstream/query.proto",
}

func (m *QueryAllPaymentStreamRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryAllPaymentStreamRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryAllPaymentStreamRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryAllPaymentStreamResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryAllPaymentStreamResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryAllPaymentStreamResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	if len(m.PaymentStreams) > 0 {
		for iNdEx := len(m.PaymentStreams) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.PaymentStreams[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintQuery(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func (m *QueryPaymentStreamsRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryPaymentStreamsRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryPaymentStreamsRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	if len(m.Status) > 0 {
		i -= len(m.Status)
		copy(dAtA[i:], m.Status)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.Status)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryPaymentStreamsResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryPaymentStreamsResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryPaymentStreamsResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	if len(m.PaymentStreams) > 0 {
		for iNdEx := len(m.PaymentStreams) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.PaymentStreams[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintQuery(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func (m *QuerySenderPaymentStreamsRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QuerySenderPaymentStreamsRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QuerySenderPaymentStreamsRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	if len(m.Sender) > 0 {
		i -= len(m.Sender)
		copy(dAtA[i:], m.Sender)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.Sender)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryRecipientPaymentStreamsRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryRecipientPaymentStreamsRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryRecipientPaymentStreamsRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	if len(m.Recipient) > 0 {
		i -= len(m.Recipient)
		copy(dAtA[i:], m.Recipient)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.Recipient)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintQuery(dAtA []byte, offset int, v uint64) int {
	offset -= sovQuery(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *QueryAllPaymentStreamRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryAllPaymentStreamResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.PaymentStreams) > 0 {
		for _, e := range m.PaymentStreams {
			l = e.Size()
			n += 1 + l + sovQuery(uint64(l))
		}
	}
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryPaymentStreamsRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Status)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryPaymentStreamsResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.PaymentStreams) > 0 {
		for _, e := range m.PaymentStreams {
			l = e.Size()
			n += 1 + l + sovQuery(uint64(l))
		}
	}
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QuerySenderPaymentStreamsRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Sender)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryRecipientPaymentStreamsRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Recipient)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func sovQuery(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozQuery(x uint64) (n int) {
	return sovQuery(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *QueryAllPaymentStreamRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryAllPaymentStreamRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryAllPaymentStreamRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageRequest{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryAllPaymentStreamResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryAllPaymentStreamResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryAllPaymentStreamResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field PaymentStreams", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.PaymentStreams = append(m.PaymentStreams, PaymentStream{})
			if err := m.PaymentStreams[len(m.PaymentStreams)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageResponse{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryPaymentStreamsRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryPaymentStreamsRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryPaymentStreamsRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Status", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Status = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageRequest{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryPaymentStreamsResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryPaymentStreamsResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryPaymentStreamsResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field PaymentStreams", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.PaymentStreams = append(m.PaymentStreams, PaymentStream{})
			if err := m.PaymentStreams[len(m.PaymentStreams)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageResponse{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QuerySenderPaymentStreamsRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QuerySenderPaymentStreamsRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QuerySenderPaymentStreamsRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Sender", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Sender = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageRequest{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryRecipientPaymentStreamsRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryRecipientPaymentStreamsRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryRecipientPaymentStreamsRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Recipient", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Recipient = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageRequest{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipQuery(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthQuery
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupQuery
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthQuery
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthQuery        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowQuery          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupQuery = fmt.Errorf("proto: unexpected end of group")
)
